import { act, renderHook, waitFor } from "@testing-library/react"
import { describe, expect, it, vi } from "vitest"
import { ApiError, type ActivityApi, type CheckResult, type DashboardPage } from "../src/lib/api"
import { useActivity, type Intent } from "../src/hooks/useActivity"
import { deferred, front, page } from "./fixtures"

const query = { start: "2026-10-03", end: "2026-10-03", state: "open" as const }
const key = "00000000-0000-4000-8000-000000000099"
function fakeApi(): ActivityApi {
  return { dashboard: vi.fn(async (query) => page(query.start, query.end)),
    createFront: vi.fn(async () => front), patchFront: vi.fn(async () => front),
    writeCheck: vi.fn(async (id, day, marked) => ({ front_id: id, day, marked })),
  }
}

describe("Estado de lectura y escrituras confirmadas", () => {
  it("dibuja el estado completo confirmado por el guardado sin una lectura HTTP adicional", async () => {
    const api = fakeApi(); const response = deferred<CheckResult>()
    vi.mocked(api.writeCheck).mockReturnValueOnce(response.promise)
    api.confirmedDashboard = vi.fn(() => page(query.start, query.end, true))
    const { result } = renderHook(() => useActivity(api, query))
    await waitFor(() => expect(result.current.canWrite).toBe(true))
    let saving!: Promise<boolean>
    act(() => { saving = result.current.perform({ kind: "check", id: front.id, day: query.start, marked: true, requestId: key }) })
    expect(result.current.page?.items[0].count).toBe(0)
    expect(result.current.savingCheck?.id).toBe(front.id)
    expect(result.current.optimisticCheck).toMatchObject({ id: front.id, marked: true })
    await act(async () => { response.resolve({ front_id: front.id, day: query.start, marked: true }); await saving })
    expect(result.current.page?.items[0].count).toBe(1)
    expect(result.current.canWrite).toBe(true)
    expect(result.current.savingCheck).toBeNull()
    expect(result.current.optimisticCheck).toBeNull()
    expect(api.dashboard).toHaveBeenCalledTimes(1)
    expect(api.confirmedDashboard).toHaveBeenCalledExactlyOnceWith(key, query)
  })
  it("una lectura posterior no recupera la vista previa de una escritura ya confirmada", async () => {
    const api = fakeApi(); const refreshed = deferred<DashboardPage>()
    api.confirmedDashboard = vi.fn(() => page(query.start, query.end, false))
    vi.mocked(api.dashboard).mockResolvedValueOnce(page()).mockReturnValueOnce(refreshed.promise)
    const { result } = renderHook(() => useActivity(api, query))
    await waitFor(() => expect(result.current.canWrite).toBe(true))
    await act(async () => { await result.current.perform({ kind: "check", id: front.id, day: query.start, marked: true, requestId: key }) })
    expect(result.current.page?.items[0].count).toBe(0) // A replay can confirm a newer unmark from another tab.
    act(() => result.current.refresh())
    expect(result.current.refreshing).toBe(true)
    expect(result.current.optimisticCheck).toBeNull()
    await act(async () => { refreshed.resolve(page()) })
  })
  it("una confirmación tardía no proyecta los datos sobre otra fecha", async () => {
    const api = fakeApi(); const response = deferred<CheckResult>()
    vi.mocked(api.writeCheck).mockReturnValueOnce(response.promise)
    api.confirmedDashboard = vi.fn(() => page(query.start, query.end, true))
    const { result, rerender } = renderHook(({ day }) => useActivity(api, { start: day, end: day }), { initialProps: { day: query.start } })
    await waitFor(() => expect(result.current.canWrite).toBe(true))
    let saving!: Promise<boolean>
    act(() => { saving = result.current.perform({ kind: "check", id: front.id, day: query.start, marked: true, requestId: key }) })
    rerender({ day: "2026-10-02" })
    await act(async () => { response.resolve({ front_id: front.id, day: query.start, marked: true }); await saving })
    await waitFor(() => expect(result.current.canWrite).toBe(true))
    expect(api.confirmedDashboard).not.toHaveBeenCalled()
    expect(result.current.page?.start).toBe("2026-10-02")
    expect(result.current.page?.items[0].count).toBe(0)
  })
  it("cambiar de cliente descarta el indicador y la proyección del guardado anterior", async () => {
    const first = fakeApi(); const second = fakeApi(); const response = deferred<CheckResult>()
    vi.mocked(first.writeCheck).mockReturnValueOnce(response.promise)
    first.confirmedDashboard = vi.fn(() => page(query.start, query.end, true))
    first.forgetSnapshot = vi.fn()
    const { result, rerender } = renderHook(({ api }) => useActivity(api, query), { initialProps: { api: first } })
    await waitFor(() => expect(result.current.canWrite).toBe(true))
    let saving!: Promise<boolean>
    act(() => { saving = result.current.perform({ kind: "check", id: front.id, day: query.start, marked: true, requestId: key }) })
    rerender({ api: second })
    expect(result.current.savingCheck).toBeNull()
    expect(result.current.optimisticCheck).toBeNull()
    expect(first.forgetSnapshot).toHaveBeenCalled()
    await act(async () => { response.resolve({ front_id: front.id, day: query.start, marked: true }); await saving })
    await waitFor(() => expect(result.current.canWrite).toBe(true))
    expect(first.confirmedDashboard).not.toHaveBeenCalled()
    expect(result.current.page?.items[0].count).toBe(0)
  })
  it("un fallo al proyectar un commit confirmado recarga sin convertirlo en una escritura incierta", async () => {
    const api = fakeApi()
    api.confirmedDashboard = vi.fn(() => { throw new Error("Projection unavailable") })
    const { result } = renderHook(() => useActivity(api, query))
    await waitFor(() => expect(result.current.canWrite).toBe(true))
    await act(async () => { expect(await result.current.perform({ kind: "check", id: front.id, day: query.start, marked: true, requestId: key })).toBe(true) })
    expect(result.current.pending).toBeNull()
    expect(result.current.mutationError).toBeNull()
    expect(api.dashboard).toHaveBeenCalledTimes(2)
  })
  it("notifica el bloqueo al padre antes de llamar al transporte y lo retiene si es incierto", async () => {
    let parentLocked = false
    const observed: boolean[] = []
    const api = fakeApi()
    vi.mocked(api.writeCheck).mockImplementation(async () => {
      observed.push(parentLocked)
      throw new ApiError("network", "Respuesta perdida", true)
    })
    const { result } = renderHook(() => useActivity(api, query, (locked) => { parentLocked = locked }))
    await waitFor(() => expect(result.current.canWrite).toBe(true))
    await act(async () => { await result.current.perform({ kind: "check", id: front.id, day: query.start, marked: true, requestId: key }) })
    expect(observed).toEqual([true])
    expect(parentLocked).toBe(true)
    vi.mocked(api.writeCheck).mockImplementation(async (id, day, marked) => { observed.push(parentLocked); return { front_id: id, day, marked } })
    await act(async () => { await result.current.retry() })
    expect(observed).toEqual([true, true])
    expect(parentLocked).toBe(false)
  })
  it("carga una página sin confundir carga/error con cero registros", async () => {
    const api = fakeApi()
    const { result } = renderHook(() => useActivity(api, query))
    expect(result.current.page).toBeNull()
    await waitFor(() => expect(result.current.page?.total).toBe(1))
    expect(result.current.canWrite).toBe(true)
  })
  it("descarta respuestas anteriores al cambiar fecha y no deja editar datos obsoletos", async () => {
    const older = deferred<DashboardPage>(); const newer = deferred<DashboardPage>()
    const api = fakeApi()
    vi.mocked(api.dashboard).mockReturnValueOnce(older.promise).mockReturnValueOnce(newer.promise)
    const { result, rerender } = renderHook(({ day }) => useActivity(api, { start: day, end: day }), { initialProps: { day: "2026-10-02" } })
    rerender({ day: "2026-10-03" })
    expect(result.current.canWrite).toBe(false)
    await act(async () => { newer.resolve(page()) })
    await act(async () => { older.resolve(page("2026-10-02")) })
    expect(result.current.page?.start).toBe("2026-10-03")
  })
  it("no marca antes de confirmar, bloquea doble envío y recarga tras éxito", async () => {
    const api = fakeApi(); const response = deferred<CheckResult>()
    vi.mocked(api.writeCheck).mockReturnValueOnce(response.promise)
    const { result } = renderHook(() => useActivity(api, query))
    await waitFor(() => expect(result.current.canWrite).toBe(true))
    const intent: Intent = { kind: "check", id: front.id, day: query.start, marked: true, requestId: key }
    let saving!: Promise<boolean>
    act(() => { saving = result.current.perform(intent); void result.current.perform(intent) })
    expect(result.current.page?.items[0].count).toBe(0)
    expect(result.current.saving).toBe(true)
    expect(api.writeCheck).toHaveBeenCalledTimes(1)
    vi.mocked(api.dashboard).mockResolvedValue(page(query.start, query.end, true))
    await act(async () => { response.resolve({ front_id: front.id, day: query.start, marked: true }); await saving })
    await waitFor(() => expect(result.current.page?.items[0].count).toBe(1))
    expect(result.current.notice).not.toBe("")
  })
  it("retira solo el aviso de éxito tras unos segundos, nunca la solicitud incierta", async () => {
    vi.useFakeTimers()
    const api = fakeApi()
    const { result, unmount } = renderHook(() => useActivity(api, query))
    try {
      await act(async () => {})
      await act(async () => { await result.current.perform({ kind: "check", id: front.id, day: query.start, marked: true, requestId: key }) })
      expect(result.current.notice).toBe("Cambio confirmado por el servidor.")
      act(() => vi.advanceTimersByTime(6000))
      expect(result.current.notice).toBe("")
      vi.mocked(api.writeCheck).mockRejectedValueOnce(new ApiError("network", "Respuesta perdida", true))
      await act(async () => { await result.current.perform({ kind: "check", id: front.id, day: query.start, marked: false, requestId: key }) })
      act(() => vi.advanceTimersByTime(60000))
      expect(result.current.pending).toMatchObject({ requestId: key })
      expect(result.current.mutationError?.uncertain).toBe(true)
      expect(api.writeCheck).toHaveBeenCalledTimes(2)
    } finally { unmount(); vi.useRealTimers() }
  })
  it("conserva la página confirmada y bloquea escrituras mientras refresca la misma consulta", async () => {
    const api = fakeApi(); const refreshed = deferred<DashboardPage>()
    vi.mocked(api.dashboard).mockResolvedValueOnce(page()).mockReturnValueOnce(refreshed.promise)
    const { result } = renderHook(() => useActivity(api, query))
    await waitFor(() => expect(result.current.canWrite).toBe(true))
    const previous = result.current.page
    await act(async () => { await result.current.perform({ kind: "check", id: front.id, day: query.start, marked: true, requestId: key }) })
    expect(result.current.page).toBe(previous)
    expect(result.current.page?.items[0].count).toBe(0) // Not an optimistic checkbox.
    expect(result.current.loading).toBe(false)
    expect(result.current.refreshing).toBe(true)
    expect(result.current.canWrite).toBe(false)
    await act(async () => { refreshed.resolve(page(query.start, query.end, true)) })
    expect(result.current.page?.items[0].count).toBe(1)
    expect(result.current.refreshing).toBe(false)
    expect(result.current.canWrite).toBe(true)
  })
  it("un error de actualización retira la página retenida y no la deja editable", async () => {
    const api = fakeApi(); const refreshed = deferred<DashboardPage>()
    vi.mocked(api.dashboard).mockResolvedValueOnce(page()).mockReturnValueOnce(refreshed.promise)
    const { result } = renderHook(() => useActivity(api, query))
    await waitFor(() => expect(result.current.canWrite).toBe(true))
    act(() => result.current.refresh())
    expect(result.current.page).not.toBeNull()
    expect(result.current.canWrite).toBe(false)
    await act(async () => { refreshed.reject(new ApiError("unauthorized", "Sesión no válida")) })
    expect(result.current.page).toBeNull()
    expect(result.current.canWrite).toBe(false)
    expect(result.current.error?.kind).toBe("unauthorized")
  })
  it("volver a una consulta anterior no reutiliza una página vieja como actual", async () => {
    const api = fakeApi(); const newRead = deferred<DashboardPage>()
    vi.mocked(api.dashboard).mockResolvedValueOnce(page()).mockReturnValue(newRead.promise)
    const { result, rerender } = renderHook(({ day }) => useActivity(api, { start: day, end: day }), { initialProps: { day: query.start } })
    await waitFor(() => expect(result.current.canWrite).toBe(true))
    rerender({ day: "2026-10-02" })
    expect(result.current.page).toBeNull()
    rerender({ day: query.start })
    expect(result.current.page).toBeNull()
    expect(result.current.canWrite).toBe(false)
    await act(async () => { newRead.resolve(page()) })
    expect(result.current.canWrite).toBe(true)
  })
  it("reintenta el alta con misma identidad y contenido aunque se cambie de vista/fecha", async () => {
    const api = fakeApi()
    vi.mocked(api.createFront).mockRejectedValueOnce(new ApiError("network", "Sin confirmación", true)).mockResolvedValueOnce(front)
    const { result, rerender } = renderHook(({ day }) => useActivity(api, { start: day, end: day }), { initialProps: { day: query.start } })
    await waitFor(() => expect(result.current.canWrite).toBe(true))
    const intent: Intent = { kind: "create", data: { name: "Guitarra", reference: null, state: "open" }, requestId: key }
    await act(async () => { expect(await result.current.perform(intent)).toBe(false) })
    intent.data.name = "Changed draft"
    expect(result.current.pending?.kind).toBe("create")
    expect(result.current.canWrite).toBe(false)
    expect(result.current.notice).toBe("")
    rerender({ day: "2026-10-04" })
    await act(async () => { expect(await result.current.retry()).toBe(true) })
    expect(api.createFront).toHaveBeenNthCalledWith(1, { name: "Guitarra", reference: null, state: "open" }, key)
    expect(api.createFront).toHaveBeenNthCalledWith(2, { name: "Guitarra", reference: null, state: "open" }, key)
    expect(result.current.pending).toBeNull()
  })
  it("mantiene la fecha y el valor deseado de un check al reintentar", async () => {
    const api = fakeApi()
    vi.mocked(api.writeCheck).mockRejectedValueOnce(new ApiError("unavailable", "Incierto", true))
    const { result, rerender } = renderHook(({ day }) => useActivity(api, { start: day, end: day }), { initialProps: { day: query.start } })
    await waitFor(() => expect(result.current.canWrite).toBe(true))
    await act(async () => { await result.current.perform({ kind: "check", id: front.id, day: query.start, marked: false, requestId: key }) })
    rerender({ day: "2026-10-04" })
    await act(async () => { await result.current.retry() })
    expect(api.writeCheck).toHaveBeenNthCalledWith(2, front.id, "2026-10-03", false, key)
  })
  it.each(["unauthorized", "access-pending"] as const)("un reintento %s no borra la incertidumbre ni identidad de la solicitud original", async (kind) => {
    const client = fakeApi()
    vi.mocked(client.createFront)
      .mockRejectedValueOnce(new ApiError("network", "Respuesta perdida", true))
      .mockRejectedValueOnce(new ApiError(kind, "Reintento denegado"))
      .mockResolvedValueOnce(front)
    const { result } = renderHook(() => useActivity(client, query))
    await waitFor(() => expect(result.current.canWrite).toBe(true))
    const intent: Intent = { kind: "create", data: { name: "Guitarra", reference: null, state: "open" }, requestId: key }
    await act(async () => { await result.current.perform(intent) })
    await act(async () => { expect(await result.current.retry()).toBe(false) })
    expect(result.current.pending).toEqual(intent)
    expect(result.current.mutationError?.uncertain).toBe(true)
    expect(result.current.error?.kind).toBe(kind)
    expect(result.current.notice).toBe("")
    act(() => result.current.refresh())
    await waitFor(() => expect(result.current.page).not.toBeNull())
    expect(result.current.canWrite).toBe(false)
    await act(async () => { expect(await result.current.retry()).toBe(true) })
    expect(client.createFront).toHaveBeenCalledTimes(3)
    expect(vi.mocked(client.createFront).mock.calls.every((args) => JSON.stringify(args) === JSON.stringify([intent.data, key]))).toBe(true)
    expect(result.current.pending).toBeNull()
  })
  it("un rechazo definitivo no deja una escritura pendiente ni borra las reglas de acceso", async () => {
    const api = fakeApi()
    vi.mocked(api.createFront).mockRejectedValue(new ApiError("access-pending", "Privado"))
    const { result } = renderHook(() => useActivity(api, query))
    await waitFor(() => expect(result.current.canWrite).toBe(true))
    await act(async () => { await result.current.perform({ kind: "create", data: front, requestId: key }) })
    expect(result.current.pending).toBeNull()
    expect(result.current.error?.kind).toBe("access-pending")
    expect(result.current.page).toBeNull()
    expect(result.current.canWrite).toBe(false)
  })
  it("cambiar el cliente oculta la página anterior y conserva la intención incierta para el nuevo cliente", async () => {
    const older = fakeApi(); const newer = fakeApi(); const load = deferred<DashboardPage>()
    vi.mocked(older.writeCheck).mockRejectedValueOnce(new ApiError("network", "Respuesta perdida", true))
    vi.mocked(newer.dashboard).mockReturnValueOnce(load.promise)
    const { result, rerender } = renderHook(({ client }) => useActivity(client, query), { initialProps: { client: older } })
    await waitFor(() => expect(result.current.canWrite).toBe(true))
    const intent: Intent = { kind: "check", id: front.id, day: query.start, marked: true, requestId: key }
    await act(async () => { await result.current.perform(intent) })
    rerender({ client: newer })
    expect(result.current.page).toBeNull()
    expect(result.current.loading).toBe(true)
    expect(result.current.pending).toEqual(intent)
    await act(async () => { load.resolve(page()) })
    expect(result.current.canWrite).toBe(false)
    await act(async () => { expect(await result.current.retry()).toBe(true) })
    expect(newer.writeCheck).toHaveBeenCalledExactlyOnceWith(front.id, query.start, true, key)
    expect(older.writeCheck).toHaveBeenCalledTimes(1)
  })
  it("una denegación tardía del cliente anterior no invalida la nueva lectura", async () => {
    const older = fakeApi(); const newer = fakeApi(); const write = deferred<CheckResult>()
    vi.mocked(older.writeCheck).mockReturnValueOnce(write.promise)
    const { result, rerender } = renderHook(({ client }) => useActivity(client, query), { initialProps: { client: older } })
    await waitFor(() => expect(result.current.canWrite).toBe(true))
    let saving!: Promise<boolean>
    act(() => { saving = result.current.perform({ kind: "check", id: front.id, day: query.start, marked: true, requestId: key }) })
    rerender({ client: newer })
    await waitFor(() => expect(newer.dashboard).toHaveBeenCalledTimes(1))
    await waitFor(() => expect(result.current.page).not.toBeNull())
    await act(async () => { write.reject(new ApiError("unauthorized", "Sesión anterior")); await saving })
    expect(result.current.page).not.toBeNull()
    expect(result.current.error).toBeNull()
  })
  it("reanudar la misma consulta tras ocultar la sesión espera una lectura nueva", async () => {
    const client = fakeApi(); const load = deferred<DashboardPage>()
    const { result, rerender } = renderHook(({ enabled }) => useActivity(client, enabled ? query : null), { initialProps: { enabled: true } })
    await waitFor(() => expect(result.current.canWrite).toBe(true))
    rerender({ enabled: false })
    expect(result.current.page).toBeNull()
    vi.mocked(client.dashboard).mockReturnValueOnce(load.promise)
    rerender({ enabled: true })
    expect(result.current.page).toBeNull()
    expect(result.current.canWrite).toBe(false)
    await act(async () => { load.resolve(page()) })
    expect(result.current.canWrite).toBe(true)
  })
  it("no consulta ni permite escribir con un período inválido", () => {
    const api = fakeApi()
    const { result } = renderHook(() => useActivity(api, null))
    expect(api.dashboard).not.toHaveBeenCalled()
    expect(result.current.canWrite).toBe(false)
  })
})
