import { act, fireEvent, render, screen, waitFor, within } from "@testing-library/react"
import userEvent from "@testing-library/user-event"
import { describe, expect, it, vi } from "vitest"
import App from "../src/App"
import { ApiError, type ActivityApi, type CheckResult, type DashboardPage } from "../src/lib/api"
import { deferred, front, page } from "./fixtures"
import { daysInWindow } from "../src/lib/dates"

const clock = () => new Date("2026-10-03T12:00:00Z")
function api(): ActivityApi {
  return { dashboard: vi.fn(async (q) => ({ ...page(q.start, q.end), offset: q.offset ?? 0 })),
    createFront: vi.fn(async () => front), patchFront: vi.fn(async () => front),
    writeCheck: vi.fn(async (id, day, marked) => ({ front_id: id, day, marked })) }
}

describe("Vistas de registro y dashboard", () => {
  it.each([true, false])("dibuja el check %s en el clic y guarda en segundo plano", async marked => {
    const client = api(); const response = deferred<CheckResult>()
    vi.mocked(client.dashboard).mockResolvedValue(page("2026-10-03", "2026-10-03", !marked))
    vi.mocked(client.writeCheck).mockReturnValueOnce(response.promise)
    client.confirmedDashboard = vi.fn(() => page("2026-10-03", "2026-10-03", marked))
    render(<App api={client} clock={clock} />)
    const check = await screen.findByRole("checkbox", { name: "Actividad en Guitarra" })
    await userEvent.click(check)
    expect(check.getAttribute("aria-busy")).toBe("true")
    expect(check.getAttribute("aria-checked")).toBe(String(marked))
    expect(screen.getByRole("checkbox", { name: "Actividad en Guitarra", description: `${marked ? "Actividad marcada" : "Actividad desmarcada"}; guardando…` })).toBe(check)
    await userEvent.click(check)
    expect(client.writeCheck).toHaveBeenCalledTimes(1)
    await act(async () => { response.resolve({ front_id: front.id, day: "2026-10-03", marked }) })
    expect(check.getAttribute("aria-checked")).toBe(String(marked))
    expect(check.getAttribute("aria-busy")).toBe("false")
    expect(check.getAttribute("aria-disabled")).toBe("false")
    expect(client.dashboard).toHaveBeenCalledTimes(1)
    expect(document.activeElement).toBe(check)
  })
  it.each([true, false])("revierte el check %s al estado confirmado si el servidor rechaza el guardado", async marked => {
    const client = api(); const response = deferred<CheckResult>()
    vi.mocked(client.dashboard).mockResolvedValue(page("2026-10-03", "2026-10-03", !marked))
    vi.mocked(client.writeCheck).mockReturnValueOnce(response.promise)
    render(<App api={client} clock={clock} />)
    const check = await screen.findByRole("checkbox", { name: "Actividad en Guitarra" })
    await userEvent.click(check)
    expect(check.getAttribute("aria-checked")).toBe(String(marked))
    await act(async () => { response.reject(new ApiError("unavailable", "Escrituras temporalmente desactivadas.")) })
    expect(check.getAttribute("aria-checked")).toBe(String(!marked))
    expect(check.getAttribute("aria-busy")).toBe("false")
    expect(check.getAttribute("aria-disabled")).toBe("false")
    expect(screen.getByRole("alert").textContent).toContain("El cambio no se ha guardado")
    expect(client.writeCheck).toHaveBeenCalledTimes(1)
    expect(document.activeElement).toBe(check)
  })
  it("una respuesta perdida retira la vista previa y mantiene la identidad del reintento", async () => {
    const client = api(); const response = deferred<CheckResult>()
    vi.mocked(client.writeCheck).mockReturnValueOnce(response.promise).mockResolvedValueOnce({ front_id: front.id, day: "2026-10-03", marked: true })
    client.confirmedDashboard = vi.fn(() => page("2026-10-03", "2026-10-03", true))
    render(<App api={client} clock={clock} />)
    const check = await screen.findByRole("checkbox", { name: "Actividad en Guitarra" })
    await userEvent.click(check)
    expect(check.getAttribute("aria-checked")).toBe("true")
    const original = vi.mocked(client.writeCheck).mock.calls[0]
    await act(async () => { response.reject(new ApiError("network", "No podemos confirmar el resultado.", true)) })
    expect(check.getAttribute("aria-checked")).toBe("false")
    expect(check.getAttribute("aria-disabled")).toBe("true")
    expect(client.writeCheck).toHaveBeenCalledTimes(1)
    await userEvent.click(screen.getByRole("button", { name: "Reintentar solicitud" }))
    await waitFor(() => expect(check.getAttribute("aria-disabled")).toBe("false"))
    expect(vi.mocked(client.writeCheck).mock.calls[1]).toEqual(original)
    expect(check.getAttribute("aria-checked")).toBe("true")
  })
  it("la vista previa de un check no se aplica a otra fecha", async () => {
    const client = api(); const response = deferred<CheckResult>()
    vi.mocked(client.writeCheck).mockReturnValueOnce(response.promise)
    render(<App api={client} clock={clock} />)
    await userEvent.click(await screen.findByRole("checkbox", { name: "Actividad en Guitarra" }))
    expect(screen.getByRole("checkbox").getAttribute("aria-checked")).toBe("true")
    fireEvent.change(screen.getByLabelText("Fecha de registro"), { target: { value: "2026-10-02" } })
    await waitFor(() => expect(screen.getByRole("checkbox").getAttribute("aria-busy")).toBe("false"))
    expect(screen.getByRole("checkbox").getAttribute("aria-checked")).toBe("false")
    await act(async () => { response.resolve({ front_id: front.id, day: "2026-10-03", marked: true }) })
    expect(screen.getByRole("checkbox").getAttribute("aria-checked")).toBe("false")
  })
  it.each(["open", "standby", "archived"] as const)("elimina a la papelera y restaura un frente %s con su historial", async state => {
    const client = api(); let trashed = false
    const saved = { ...front, state }
    client.trashFront = vi.fn(async () => { trashed = true; return { ...saved, trashed_at: "2026-10-03T12:00:00Z" } })
    client.restoreFront = vi.fn(async () => { trashed = false; return { ...saved, trashed_at: null } })
    vi.mocked(client.dashboard).mockImplementation(async q => {
      const data = page(q.start, q.end, true)
      const items = !!q.trashed === trashed ? [{ ...data.items[0], front: saved }] : []
      return { ...data, items, total: items.length }
    })
    render(<App api={client} clock={clock} />)
    await userEvent.click(await screen.findByRole("button", { name: "Editar Guitarra" }))
    await userEvent.click(screen.getByRole("button", { name: "Eliminar frente" }))
    await waitFor(() => expect(screen.queryByRole("dialog")).toBeNull())
    expect(screen.queryByText("Guitarra")).toBeNull()
    await userEvent.click(screen.getByRole("button", { name: "Papelera" }))
    const restore = await screen.findByRole("button", { name: "Restaurar Guitarra" })
    expect(screen.queryByRole("checkbox")).toBeNull()
    expect(screen.queryByRole("button", { name: "Editar Guitarra" })).toBeNull()
    expect(client.dashboard).toHaveBeenLastCalledWith(expect.objectContaining({ trashed: true, state: "all" }), expect.any(AbortSignal))
    await userEvent.click(restore)
    await screen.findByText("La papelera está vacía")
    await userEvent.click(screen.getByRole("button", { name: "Registro diario" }))
    expect((await screen.findByRole("checkbox", { name: "Actividad en Guitarra" })).getAttribute("aria-checked")).toBe("true")
    expect(client.restoreFront).toHaveBeenCalledWith(front.id, expect.any(String))
    expect(client.writeCheck).not.toHaveBeenCalled()
    expect(client.patchFront).not.toHaveBeenCalled()
  })
  it("reintenta una eliminación incierta con la misma identidad y conserva el editor hasta confirmar", async () => {
    const client = api(); let trashed = false
    client.trashFront = vi.fn().mockRejectedValueOnce(new ApiError("network", "Resultado sin confirmar.", true)).mockImplementation(async () => { trashed = true; return { ...front, trashed_at: "2026-10-03T12:00:00Z" } })
    client.restoreFront = vi.fn(async () => front)
    vi.mocked(client.dashboard).mockImplementation(async q => ({ ...page(q.start, q.end), items: trashed ? [] : page(q.start, q.end).items, total: trashed ? 0 : 1 }))
    render(<App api={client} clock={clock} />)
    await userEvent.click(await screen.findByRole("button", { name: "Editar Guitarra" }))
    await userEvent.click(screen.getByRole("button", { name: "Eliminar frente" }))
    await screen.findByRole("button", { name: "Reintentar solicitud" })
    expect(screen.getByRole("dialog")).toBeTruthy()
    expect(screen.getByRole("button", { name: "Eliminar frente" }).hasAttribute("disabled")).toBe(true)
    await userEvent.keyboard("{Escape}")
    expect(screen.getByRole("dialog")).toBeTruthy()
    await userEvent.click(screen.getByRole("button", { name: "Reintentar solicitud" }))
    await waitFor(() => expect(screen.queryByRole("dialog")).toBeNull())
    expect(vi.mocked(client.trashFront).mock.calls[1]).toEqual(vi.mocked(client.trashFront).mock.calls[0])
    expect(screen.queryByText("Guitarra")).toBeNull()
  })
  it.each([false, true])("recupera el foco tras restaurar, sin quitárselo a otra acción: %s", async movedFocus => {
    const client = api(); const response = deferred<typeof front>()
    client.trashFront = vi.fn(async () => front)
    client.restoreFront = vi.fn(() => response.promise)
    client.confirmedDashboard = vi.fn((_id, q) => ({ ...page(q.start, q.end), items: [], total: 0 }))
    render(<App api={client} clock={clock} />)
    await screen.findByText("Guitarra")
    const navigation = screen.getByRole("button", { name: "Papelera" })
    await userEvent.click(navigation)
    const restore = await screen.findByRole("button", { name: "Restaurar Guitarra" })
    await userEvent.click(restore)
    expect(restore.hasAttribute("disabled")).toBe(true)
    restore.blur() // Firefox blurs a focused native button when it is disabled.
    const search = screen.getByRole("searchbox", { name: "Buscar por nombre" })
    if (movedFocus) search.focus()
    await act(async () => { response.resolve(front) })
    await screen.findByText("La papelera está vacía")
    expect(document.activeElement).toBe(movedFocus ? search : navigation)
  })
  it("conserva la marca sin la ilustración alternativa ni controles de laboratorio", async () => {
    const client = api()
    render(<App api={client} clock={clock} />)
    await screen.findByText("Guitarra")
    const mark = document.querySelector(".brand-mark")
    expect(mark).not.toBeNull()
    expect(mark?.getAttribute("aria-hidden")).toBe("true")
    expect(mark?.querySelector("button, input, a, [tabindex]")).toBeNull()
    expect(screen.getByText("Activity Hub")).toBeTruthy()
    expect(document.querySelector(".desk-decoration")).toBeNull()
    expect(screen.queryByText(/LABORATORIO|HOY SIMULADO|Solo en esta maqueta/)).toBeNull()
    expect(screen.queryByLabelText("Aspecto")).toBeNull()
    expect(screen.queryByRole("button", { name: "Reiniciar muestra" })).toBeNull()
    expect(client.createFront).not.toHaveBeenCalled()
    expect(client.writeCheck).not.toHaveBeenCalled()
    expect(client.patchFront).not.toHaveBeenCalled()
  })
  it("muestra acceso pendiente sin frentes inventados y permite recorrer las vistas", async () => {
    const client = api()
    vi.mocked(client.dashboard).mockRejectedValue(new ApiError("access-pending", "El acceso privado todavía no está configurado."))
    render(<App api={client} clock={clock} />)
    expect(await screen.findByRole("heading", { name: "Acceso privado pendiente" })).toBeTruthy()
    expect(screen.queryByRole("checkbox")).toBeNull()
    await userEvent.click(screen.getByRole("button", { name: "Dashboard" }))
    expect(screen.getByRole("heading", { name: "Dashboard" })).toBeTruthy()
    expect(client.createFront).not.toHaveBeenCalled()
    expect(client.writeCheck).not.toHaveBeenCalled()
  })
  it("distingue carga, error de red y vacío confirmado", async () => {
    const client = api(); const load = deferred<DashboardPage>()
    vi.mocked(client.dashboard).mockReturnValueOnce(load.promise).mockResolvedValueOnce({ ...page(), items: [], total: 0 })
    render(<App api={client} clock={clock} />)
    expect(screen.getByText("Cargando tus frentes…")).toBeTruthy()
    expect(screen.queryByText("No hay frentes en esta vista")).toBeNull()
    await act(async () => { load.reject(new ApiError("network", "No se ha podido conectar con el servidor.")) })
    expect(await screen.findByRole("button", { name: "Reintentar carga" })).toBeTruthy()
    expect(screen.queryByText("No hay frentes en esta vista")).toBeNull()
    await userEvent.click(screen.getByRole("button", { name: "Reintentar carga" }))
    expect(await screen.findByText("No hay frentes en esta vista")).toBeTruthy()
  })
  it("mantiene la vista anterior sin permitir checks hasta recibir la vista elegida", async () => {
    const client = api(); const dashboard = deferred<DashboardPage>()
    vi.mocked(client.dashboard).mockResolvedValueOnce(page()).mockReturnValueOnce(dashboard.promise)
    render(<App api={client} clock={clock} />)
    const check = await screen.findByRole("checkbox", { name: "Actividad en Guitarra" })
    const list = screen.getByRole("list", { name: "Frentes del registro diario" })
    await userEvent.click(screen.getByRole("button", { name: "Dashboard" }))
    expect(screen.getByRole("heading", { name: "Registro diario" })).toBeTruthy()
    expect(screen.getByRole("list", { name: "Frentes del registro diario" })).toBe(list)
    expect(check.isConnected).toBe(true)
    expect(check.getAttribute("aria-disabled")).toBe("true")
    expect(list.getAttribute("aria-busy")).toBe("true")
    expect(screen.getByRole("main").hasAttribute("inert")).toBe(true)
    expect(screen.queryByText("Cargando tus frentes…")).toBeNull()
    await userEvent.click(check)
    expect(client.writeCheck).not.toHaveBeenCalled()
    await act(async () => { dashboard.resolve(page("2026-09-06", "2026-10-03", true)) })
    expect(screen.getByRole("heading", { name: "Dashboard" })).toBeTruthy()
    expect(screen.getByLabelText("3,6 % de los días seleccionados")).toBeTruthy()
    expect(screen.queryByRole("checkbox")).toBeNull()
    expect(screen.getByRole("main").hasAttribute("inert")).toBe(false)
  })
  it("descarta respuestas de navegación anteriores si se cambia de vista durante la carga", async () => {
    const client = api(); const dashboard = deferred<DashboardPage>(); const daily = deferred<DashboardPage>()
    vi.mocked(client.dashboard).mockResolvedValueOnce(page()).mockReturnValueOnce(dashboard.promise).mockReturnValueOnce(daily.promise)
    render(<App api={client} clock={clock} />)
    await screen.findByText("Guitarra")
    await userEvent.click(screen.getByRole("button", { name: "Dashboard" }))
    await userEvent.click(screen.getByRole("button", { name: "Registro diario" }))
    await act(async () => { dashboard.resolve(page("2026-09-06", "2026-10-03", true)) })
    expect(screen.getByRole("heading", { name: "Registro diario" })).toBeTruthy()
    expect(screen.queryByLabelText(/% de los días seleccionados/)).toBeNull()
    expect(screen.getByRole("main").hasAttribute("inert")).toBe(true)
    await act(async () => { daily.resolve(page("2026-10-03", "2026-10-03", true)) })
    expect(screen.getByRole("checkbox", { name: "Actividad en Guitarra" }).getAttribute("aria-checked")).toBe("true")
    expect(screen.getByRole("main").hasAttribute("inert")).toBe(false)
  })
  it("no conserva una vista de otro cliente o sesión durante la navegación", async () => {
    const first = api(); const second = api(); const dashboard = deferred<DashboardPage>(); const replacement = deferred<DashboardPage>()
    vi.mocked(first.dashboard).mockResolvedValueOnce(page()).mockReturnValueOnce(dashboard.promise)
    vi.mocked(second.dashboard).mockReturnValue(replacement.promise)
    const app = render(<App api={first} clock={clock} />)
    await screen.findByText("Guitarra")
    await userEvent.click(screen.getByRole("button", { name: "Dashboard" }))
    expect(screen.getByText("Guitarra")).toBeTruthy()
    app.rerender(<App api={second} clock={clock} />)
    expect(screen.queryByText("Guitarra")).toBeNull()
    expect(screen.getByText("Cargando tus frentes…")).toBeTruthy()
    await act(async () => { dashboard.resolve(page("2026-09-06", "2026-10-03", true)) })
    expect(screen.queryByText("Guitarra")).toBeNull()
    await act(async () => { replacement.resolve({ ...page("2026-09-06", "2026-10-03"), items: [], total: 0 }) })
    expect(screen.getByText("No hay frentes en esta vista")).toBeTruthy()
  })
  it("muestra el error de la vista elegida y permite reintentar sin mantener contenido antiguo", async () => {
    const client = api(); const dashboard = deferred<DashboardPage>()
    vi.mocked(client.dashboard).mockResolvedValueOnce(page()).mockReturnValueOnce(dashboard.promise)
    render(<App api={client} clock={clock} />)
    await screen.findByText("Guitarra")
    await userEvent.click(screen.getByRole("button", { name: "Dashboard" }))
    await act(async () => { dashboard.reject(new ApiError("network", "No se ha podido conectar con el servidor.")) })
    expect(screen.getByRole("heading", { name: "Dashboard" })).toBeTruthy()
    expect(screen.queryByText("Guitarra")).toBeNull()
    expect(screen.getByRole("main").hasAttribute("inert")).toBe(false)
    await userEvent.click(screen.getByRole("button", { name: "Reintentar carga" }))
    expect(await screen.findByRole("list", { name: "Frentes del dashboard" })).toBeTruthy()
  })
  it("conserva una solicitud incierta y su identidad al cambiar de vista", async () => {
    const client = api(); const dashboard = deferred<DashboardPage>()
    vi.mocked(client.dashboard).mockResolvedValueOnce(page()).mockReturnValueOnce(dashboard.promise)
    vi.mocked(client.writeCheck).mockRejectedValueOnce(new ApiError("network", "Resultado sin confirmar.", true))
    render(<App api={client} clock={clock} />)
    await userEvent.click(await screen.findByRole("checkbox", { name: "Actividad en Guitarra" }))
    await screen.findByRole("button", { name: "Reintentar solicitud" })
    const original = vi.mocked(client.writeCheck).mock.calls[0]
    await userEvent.click(screen.getByRole("button", { name: "Dashboard" }))
    await act(async () => { dashboard.resolve(page("2026-09-06", "2026-10-03")) })
    expect(screen.getByRole("heading", { name: "Dashboard" })).toBeTruthy()
    expect(screen.getByText(/Solicitud del 3 de octubre de 2026/)).toBeTruthy()
    await userEvent.click(screen.getByRole("button", { name: "Reintentar solicitud" }))
    expect(client.writeCheck).toHaveBeenCalledTimes(2)
    expect(vi.mocked(client.writeCheck).mock.calls[1]).toEqual(original)
    expect(screen.queryByRole("button", { name: "Reintentar solicitud" })).toBeNull()
  })
  it("envía una orden explícita por ID y fecha seleccionada, incluso en archivados", async () => {
    const client = api()
    vi.mocked(client.dashboard).mockImplementation(async (q) => {
      const data = page(q.start, q.end); data.items[0].front.state = "archived"; return data
    })
    render(<App api={client} clock={clock} />)
    await screen.findByText("Guitarra")
    await userEvent.selectOptions(screen.getByLabelText("Estado"), "archived")
    fireEvent.change(screen.getByLabelText("Fecha de registro"), { target: { value: "2026-10-02" } })
    const checkbox = await screen.findByRole("checkbox", { name: "Actividad en Guitarra" })
    await waitFor(() => expect(checkbox.getAttribute("aria-disabled")).toBe("false"))
    await userEvent.click(checkbox)
    await waitFor(() => expect(client.writeCheck).toHaveBeenCalledWith(front.id, "2026-10-02", true, expect.any(String)))
    expect(client.patchFront).not.toHaveBeenCalled()
  })
  it("mantiene el mismo check y la lista en el DOM durante la actualización confirmada", async () => {
    const client = api(); const response = deferred<CheckResult>(); const refreshed = deferred<DashboardPage>()
    vi.mocked(client.writeCheck).mockReturnValueOnce(response.promise)
    vi.mocked(client.dashboard).mockResolvedValueOnce(page()).mockReturnValueOnce(refreshed.promise)
    render(<App api={client} clock={clock} />)
    const checkbox = await screen.findByRole("checkbox", { name: "Actividad en Guitarra" })
    const list = screen.getByRole("list", { name: "Frentes del registro diario" })
    await userEvent.click(checkbox)
    expect(screen.queryByText(/Enviando solicitud|Espera la confirmación/)).toBeNull()
    expect(list.getAttribute("aria-busy")).toBe("true")
    expect(checkbox.getAttribute("aria-checked")).toBe("true")
    expect(checkbox.getAttribute("aria-disabled")).toBe("true")
    await act(async () => { response.resolve({ front_id: front.id, day: "2026-10-03", marked: true }) })
    await waitFor(() => expect(client.dashboard).toHaveBeenCalledTimes(2))
    expect(checkbox.isConnected).toBe(true)
    expect(screen.getByRole("list", { name: "Frentes del registro diario" })).toBe(list)
    expect(checkbox.getAttribute("aria-checked")).toBe("true")
    expect(checkbox.getAttribute("aria-disabled")).toBe("true")
    await userEvent.click(checkbox)
    await userEvent.keyboard(" ")
    expect(client.writeCheck).toHaveBeenCalledTimes(1)
    expect(document.activeElement).toBe(checkbox)
    expect(screen.queryByText("Cargando tus frentes…")).toBeNull()
    await act(async () => { refreshed.resolve(page("2026-10-03", "2026-10-03", true)) })
    expect(screen.getByRole("checkbox", { name: "Actividad en Guitarra" })).toBe(checkbox)
    expect(checkbox.getAttribute("aria-checked")).toBe("true")
    expect(checkbox.getAttribute("aria-disabled")).toBe("false")
    expect(document.activeElement).toBe(checkbox)
    expect(screen.queryByText("Cambio confirmado por el servidor.")).toBeNull()
  })
  it("distingue frentes con el mismo nombre por ID al marcar", async () => {
    const client = api()
    const secondId = "00000000-0000-4000-8000-000000000002"
    vi.mocked(client.dashboard).mockImplementation(async (q) => {
      const data = page(q.start, q.end)
      return { ...data, total: 2, items: [data.items[0], { ...data.items[0], front: { ...front, id: secondId } }] }
    })
    render(<App api={client} clock={clock} />)
    const checks = await screen.findAllByRole("checkbox", { name: "Actividad en Guitarra" })
    await userEvent.click(checks[1])
    await waitFor(() => expect(client.writeCheck).toHaveBeenCalledWith(secondId, "2026-10-03", true, expect.any(String)))
  })
  it("renderiza nombres como texto y no crea enlaces ejecutables", async () => {
    const client = api()
    const name = '<img src=x onerror="alert(1)">'
    vi.mocked(client.dashboard).mockImplementation(async (q) => {
      const data = page(q.start, q.end)
      data.items[0].front = { ...front, name, reference: "javascript:alert(1)" }
      return data
    })
    render(<App api={client} clock={clock} />)
    expect(await screen.findByRole("heading", { name })).toBeTruthy()
    expect(document.querySelector("img")).toBeNull()
    expect(screen.queryByRole("link", { name: /Referencia/ })).toBeNull()
  })
  it.each(["daily", "dashboard"])("mantiene referencia y edición independientes del check en %s", async (view) => {
    const client = api()
    render(<App api={client} clock={clock} />)
    if (view === "dashboard") await userEvent.click(screen.getByRole("button", { name: "Dashboard" }))
    const link = await screen.findByRole("link", { name: "Referencia de Guitarra (nueva pestaña)" })
    expect(link.getAttribute("href")).toBe(front.reference)
    expect(link.getAttribute("target")).toBe("_blank")
    expect(link.getAttribute("rel")).toBe("noopener noreferrer")
    if (view === "daily") {
      screen.getByRole("checkbox", { name: "Actividad en Guitarra" }).focus()
      await userEvent.tab()
      expect(document.activeElement).toBe(link)
    }
    link.addEventListener("click", (event) => event.preventDefault(), { once: true })
    await userEvent.click(link)
    const edit = screen.getByRole("button", { name: "Editar Guitarra" })
    await userEvent.click(edit)
    expect((within(screen.getByRole("dialog")).getByLabelText("Enlace (opcional)") as HTMLInputElement).value).toBe(front.reference)
    await userEvent.keyboard("{Escape}")
    expect(document.activeElement).toBe(edit)
    expect(client.writeCheck).not.toHaveBeenCalled()
    expect(client.createFront).not.toHaveBeenCalled()
    expect(client.patchFront).not.toHaveBeenCalled()
  })
  it("mantiene la explicación accesible del check al compactar la fila", async () => {
    const client = api()
    let marked = false
    vi.mocked(client.dashboard).mockImplementation(async (q) => page(q.start, q.end, marked))
    vi.mocked(client.writeCheck).mockImplementation(async (id, day, value) => { marked = value; return { front_id: id, day, marked } })
    render(<App api={client} clock={clock} />)
    const checkbox = await screen.findByRole("checkbox", { name: "Actividad en Guitarra", description: "Sin actividad registrada" })
    await userEvent.click(checkbox)
    await screen.findByRole("checkbox", { name: "Actividad en Guitarra", description: "Actividad registrada" })
    expect(client.writeCheck).toHaveBeenCalledTimes(1)
  })
  it("actualiza hoy en Madrid al volver a la pestaña sin cambiar la fecha seleccionada", async () => {
    const client = api()
    let now = new Date("2026-10-03T21:59:00Z")
    render(<App api={client} clock={() => now} />)
    await screen.findByText("Guitarra")
    now = new Date("2026-10-03T22:01:00Z")
    fireEvent.focus(window)
    const date = screen.getByLabelText("Fecha de registro") as HTMLInputElement
    await waitFor(() => expect(date.max).toBe("2026-10-04"))
    expect(date.value).toBe("2026-10-03")
    await userEvent.click(screen.getByRole("checkbox", { name: "Actividad en Guitarra" }))
    await waitFor(() => expect(client.writeCheck).toHaveBeenCalledWith(front.id, "2026-10-03", true, expect.any(String)))
  })
  it("enfoca el nombre al abrir el editor y devuelve el foco al cerrar", async () => {
    render(<App api={api()} clock={clock} />)
    await screen.findByText("Guitarra")
    const opener = screen.getByRole("button", { name: "Nuevo frente" })
    await userEvent.click(opener)
    const dialog = await screen.findByRole("dialog")
    await waitFor(() => expect(document.activeElement).toBe(within(dialog).getByLabelText("Nombre")))
    await userEvent.keyboard("{Escape}")
    await waitFor(() => expect(screen.queryByRole("dialog")).toBeNull())
    expect(document.activeElement).toBe(opener)
  })
  it("crea solo al confirmar el formulario, sin marcar actividad", async () => {
    const client = api()
    render(<App api={client} clock={clock} />)
    await screen.findByText("Guitarra")
    await userEvent.click(screen.getByRole("button", { name: "Nuevo frente" }))
    const dialog = await screen.findByRole("dialog")
    await userEvent.type(within(dialog).getByLabelText("Nombre"), "  Lectura  ")
    await userEvent.type(within(dialog).getByLabelText("Enlace (opcional)"), "https://example.test/lectura")
    expect(client.createFront).not.toHaveBeenCalled()
    await userEvent.click(within(dialog).getByRole("button", { name: "Crear frente" }))
    await waitFor(() => expect(client.createFront).toHaveBeenCalledWith({ name: "Lectura", reference: "https://example.test/lectura", state: "open" }, expect.any(String)))
    expect(client.writeCheck).not.toHaveBeenCalled()
    await waitFor(() => expect(screen.queryByRole("dialog")).toBeNull())
  })
  it("edita por ID, permite limpiar un enlace y cambia estado sin tocar checks", async () => {
    const client = api()
    render(<App api={client} clock={clock} />)
    await userEvent.click(await screen.findByRole("button", { name: "Editar Guitarra" }))
    const dialog = await screen.findByRole("dialog")
    await userEvent.clear(within(dialog).getByLabelText("Enlace (opcional)"))
    await userEvent.selectOptions(within(dialog).getByLabelText("Estado del frente"), "standby")
    await userEvent.click(within(dialog).getByRole("button", { name: "Guardar cambios" }))
    await waitFor(() => expect(client.patchFront).toHaveBeenCalledWith(front.id, { name: "Guitarra", reference: null, state: "standby" }))
    expect(client.writeCheck).not.toHaveBeenCalled()
  })
  it("no permite marcar una fecha futura ni reutiliza la página de ayer como si fuera hoy", async () => {
    const client = api()
    render(<App api={client} clock={clock} />)
    await screen.findByText("Guitarra")
    fireEvent.change(screen.getByLabelText("Fecha de registro"), { target: { value: "2026-10-04" } })
    expect(await screen.findByText("Selecciona hoy o una fecha pasada.")).toBeTruthy()
    expect(screen.queryByRole("checkbox")).toBeNull()
    expect(client.writeCheck).not.toHaveBeenCalled()
  })
  it("pide orden global por actividad solo en dashboard, también al filtrar y paginar", async () => {
    const client = api()
    vi.mocked(client.dashboard).mockImplementation(async (q) => ({ ...page(q.start, q.end), total: 21, offset: q.offset ?? 0 }))
    render(<App api={client} clock={clock} />)
    await screen.findByText("Guitarra")
    expect(client.dashboard).toHaveBeenLastCalledWith(expect.objectContaining({ order: "created", offset: 0 }), expect.any(AbortSignal))
    await userEvent.click(screen.getByRole("button", { name: "Dashboard" }))
    await waitFor(() => expect(client.dashboard).toHaveBeenLastCalledWith(expect.objectContaining({ order: "activity_desc", offset: 0 }), expect.any(AbortSignal)))
    await userEvent.click(screen.getByRole("button", { name: "Página siguiente" }))
    await waitFor(() => expect(client.dashboard).toHaveBeenLastCalledWith(expect.objectContaining({ order: "activity_desc", offset: 20 }), expect.any(AbortSignal)))
    await userEvent.selectOptions(screen.getByLabelText("Estado"), "standby")
    fireEvent.change(screen.getByLabelText("Desde"), { target: { value: "2026-10-01" } })
    await waitFor(() => expect(client.dashboard).toHaveBeenLastCalledWith(expect.objectContaining({ order: "activity_desc", offset: 0, state: "standby", start: "2026-10-01" }), expect.any(AbortSignal)))
    await userEvent.click(screen.getByRole("button", { name: "Registro diario" }))
    await waitFor(() => expect(client.dashboard).toHaveBeenLastCalledWith(expect.objectContaining({ order: "created", start: "2026-10-03", end: "2026-10-03", offset: 0 }), expect.any(AbortSignal)))
  })
  it("muestra último registro global y conteo del período sin calificar los huecos", async () => {
    const client = api()
    render(<App api={client} clock={clock} />)
    await userEvent.click(screen.getByRole("button", { name: "Dashboard" }))
    fireEvent.change(screen.getByLabelText("Desde"), { target: { value: "2026-01-01" } })
    fireEvent.change(screen.getByLabelText("Hasta"), { target: { value: "2026-01-31" } })
    expect(await screen.findByText("30 de septiembre de 2026")).toBeTruthy()
    expect(screen.getByText("0 de 31 días registrados")).toBeTruthy()
    expect(screen.getByText("Sin actividad registrada", { exact: true })).toBeTruthy()
    expect(screen.queryByText(/abandono|puntuación|racha/i)).toBeNull()
  })
  it.each([
    ["2026-01-01", "2026-01-10", 4, "40", 10],
    ["2026-01-01", "2026-01-10", 0, "0", 10],
    ["2026-10-03", "2026-10-03", 1, "100", 1],
    ["2026-03-28", "2026-03-30", 2, "66,7", 3],
    ["2024-01-01", "2024-12-31", 1, "0,3", 366],
    ["2024-01-01", "2024-12-31", 365, "99,7", 366],
  ])("calcula por frente %s–%s con %i días marcados, incluidos ambos extremos", async (start, end, count, percentage, totalDays) => {
    const client = api()
    vi.mocked(client.dashboard).mockImplementation(async (q) => {
      const data = page(q.start, q.end)
      const marked = daysInWindow(q.start, q.end).slice(0, count)
      data.items[0] = { ...data.items[0], count: marked.length, marked_dates: marked }
      // There are other pages: their fronts must not affect this percentage.
      return { ...data, total: 21, offset: q.offset ?? 0 }
    })
    render(<App api={client} clock={clock} />)
    await userEvent.click(screen.getByRole("button", { name: "Dashboard" }))
    fireEvent.change(screen.getByLabelText("Desde"), { target: { value: start } })
    fireEvent.change(screen.getByLabelText("Hasta"), { target: { value: end } })
    expect(await screen.findByLabelText(`${percentage} % de los días seleccionados`)).toBeTruthy()
    expect(screen.getByText(`${count} de ${totalDays} ${totalDays === 1 ? "día registrado" : "días registrados"}`)).toBeTruthy()
    expect(screen.queryByText(/NaN|Infinity/)).toBeNull()
    expect(client.writeCheck).not.toHaveBeenCalled()
  })
  it("despliega solo el frente elegido sin consultar ni escribir y mantiene los homónimos independientes", async () => {
    const client = api()
    vi.mocked(client.dashboard).mockImplementation(async (q) => {
      const data = page(q.start, q.end, true)
      return { ...data, total: 2, items: [data.items[0], { ...data.items[0], front: { ...front, id: "00000000-0000-4000-8000-000000000002" }, marked_dates: [], count: 0 }] }
    })
    render(<App api={client} clock={clock} />)
    await userEvent.click(screen.getByRole("button", { name: "Dashboard" }))
    const titles = await screen.findAllByRole("heading", { name: "Guitarra" })
    const rows = titles.map((title) => title.closest("li")!)
    const summaries = rows.map((row) => within(row).getByText("Ver días del período"))
    const details = summaries.map((summary) => summary.closest("details")!)
    expect(details.every((detail) => !detail.open)).toBe(true)
    expect(within(rows[0]).getByLabelText("3,6 % de los días seleccionados")).toBeTruthy()
    expect(within(rows[1]).getByLabelText("0 % de los días seleccionados")).toBeTruthy()
    const reads = vi.mocked(client.dashboard).mock.calls.length
    await userEvent.click(summaries[0])
    expect(details[0].open).toBe(true)
    expect(details[1].open).toBe(false)
    const calendar = within(rows[0]).getByRole("list", { name: "Días del período de Guitarra" })
    expect(within(calendar).getAllByRole("img")).toHaveLength(28)
    expect(within(calendar).getByRole("img", { name: "6 de septiembre de 2026: Actividad registrada" })).toBeTruthy()
    expect(within(calendar).getByRole("img", { name: "3 de octubre de 2026: Sin actividad registrada" })).toBeTruthy()
    await userEvent.click(summaries[0])
    expect(details[0].open).toBe(false)
    expect(client.dashboard).toHaveBeenCalledTimes(reads)
    expect(client.createFront).not.toHaveBeenCalled()
    expect(client.patchFront).not.toHaveBeenCalled()
    expect(client.writeCheck).not.toHaveBeenCalled()
  })
  it("cambiar de período recalcula el resumen y vuelve a plegar el detalle", async () => {
    const client = api()
    vi.mocked(client.dashboard).mockImplementation(async (q) => page(q.start, q.end, true))
    render(<App api={client} clock={clock} />)
    await userEvent.click(screen.getByRole("button", { name: "Dashboard" }))
    await userEvent.click(await screen.findByText("Ver días del período"))
    expect(screen.getByText("Ver días del período").closest("details")?.open).toBe(true)
    fireEvent.change(screen.getByLabelText("Desde"), { target: { value: "2026-10-03" } })
    expect(await screen.findByText("1 de 1 día registrado")).toBeTruthy()
    expect(screen.getByLabelText("100 % de los días seleccionados")).toBeTruthy()
    expect(screen.getByText("Ver días del período").closest("details")?.open).toBe(false)
  })
  it("no presenta porcentajes para un intervalo inválido", async () => {
    render(<App api={api()} clock={clock} />)
    await userEvent.click(screen.getByRole("button", { name: "Dashboard" }))
    expect(await screen.findByLabelText("0 % de los días seleccionados")).toBeTruthy()
    fireEvent.change(screen.getByLabelText("Desde"), { target: { value: "2026-10-04" } })
    expect(screen.getByRole("alert").textContent).toContain("Selecciona fechas válidas")
    expect(screen.queryByLabelText(/% de los días seleccionados/)).toBeNull()
    expect(screen.queryByText("Ver días del período")).toBeNull()
  })
  it("pagina sin perder estado/filtros y sin suponer que la primera página es toda la lista", async () => {
    const client = api()
    vi.mocked(client.dashboard).mockImplementation(async (q) => ({ ...page(q.start, q.end), total: 21, offset: q.offset ?? 0 }))
    render(<App api={client} clock={clock} />)
    await screen.findByText("Guitarra")
    await userEvent.click(screen.getByRole("button", { name: "Página siguiente" }))
    await waitFor(() => expect(client.dashboard).toHaveBeenCalledWith(expect.objectContaining({ offset: 20, state: "open" }), expect.any(AbortSignal)))
  })
  it("vuelve a la página válida cuando una edición elimina el último resultado de la última página", async () => {
    const client = api()
    let moved = false
    vi.mocked(client.dashboard).mockImplementation(async (q) => {
      const data = page(q.start, q.end)
      return { ...data, total: moved ? 20 : 21, offset: q.offset ?? 0,
        items: moved && q.offset === 20 ? [] : data.items }
    })
    vi.mocked(client.patchFront).mockImplementation(async () => { moved = true; return { ...front, state: "standby" } })
    render(<App api={client} clock={clock} />)
    await screen.findByText("Guitarra")
    await userEvent.click(screen.getByRole("button", { name: "Página siguiente" }))
    await screen.findByText("Página 2 de 2")
    await userEvent.click(screen.getByRole("button", { name: "Editar Guitarra" }))
    const dialog = await screen.findByRole("dialog")
    await userEvent.selectOptions(within(dialog).getByLabelText("Estado del frente"), "standby")
    await userEvent.click(within(dialog).getByRole("button", { name: "Guardar cambios" }))
    expect(await screen.findByText("Página 1 de 1")).toBeTruthy()
    expect(screen.queryByText("Página 2 de 1")).toBeNull()
    expect(screen.queryByText("No hay frentes en esta vista")).toBeNull()
    expect(screen.getByText("Guitarra")).toBeTruthy()
    expect(vi.mocked(client.dashboard).mock.lastCall?.[0].offset).toBe(0)
  })
  it("desactivar la sesión oculta y aborta las lecturas y el portal sin perder el editor", async () => {
    const client = api()
    const { rerender } = render(<App api={client} clock={clock} />)
    await screen.findByText("Guitarra")
    await userEvent.click(screen.getByRole("button", { name: "Nuevo frente" }))
    await userEvent.type(screen.getByLabelText("Nombre"), "Lectura pendiente")
    const signal = vi.mocked(client.dashboard).mock.calls[0][1]
    rerender(<App api={client} clock={clock} enabled={false} />)
    expect(screen.queryByRole("dialog")).toBeNull()
    expect(screen.queryByText("Guitarra")).toBeNull()
    expect(signal?.aborted).toBe(true)
    expect(client.dashboard).toHaveBeenCalledTimes(1)
    rerender(<App api={client} clock={clock} enabled />)
    const dialog = await screen.findByRole("dialog")
    expect((within(dialog).getByLabelText("Nombre") as HTMLInputElement).value).toBe("Lectura pendiente")
    await waitFor(() => expect(client.dashboard).toHaveBeenCalledTimes(2))
  })
  it("una alta incierta ofrece reintentar la misma solicitud sin convertirla en guardada", async () => {
    const client = api()
    vi.mocked(client.createFront).mockRejectedValueOnce(new ApiError("network", "No podemos confirmar el resultado.", true)).mockResolvedValueOnce(front)
    render(<App api={client} clock={clock} />)
    await screen.findByText("Guitarra")
    await userEvent.click(screen.getByRole("button", { name: "Nuevo frente" }))
    const dialog = await screen.findByRole("dialog")
    await userEvent.type(within(dialog).getByLabelText("Nombre"), "Lectura")
    await userEvent.click(within(dialog).getByRole("button", { name: "Crear frente" }))
    const retry = await screen.findByRole("button", { name: "Reintentar solicitud" })
    expect(screen.queryByText("Cambio confirmado por el servidor.")).toBeNull()
    await userEvent.click(retry)
    await waitFor(() => expect(client.createFront).toHaveBeenCalledTimes(2))
    expect(vi.mocked(client.createFront).mock.calls[1]).toEqual(vi.mocked(client.createFront).mock.calls[0])
  })
})
