import { act, fireEvent, render, screen, waitFor, within } from "@testing-library/react"
import userEvent from "@testing-library/user-event"
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest"
import AuthenticatedApp from "../src/AuthenticatedApp"
import { createAuthClient } from "../src/lib/auth"
import { deferred, front, page } from "./fixtures"

const clock = () => new Date("2026-10-03T12:00:00Z")
const csrfA = "A".repeat(43); const csrfB = "B".repeat(43)
const accountA = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"
const accountB = "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb"
const newCode = "ABCD-EFGH-JKLM-NPQR-STUV-WXYZ-2345-6789"
const session = (csrf = csrfA, account = accountA) => ({ authenticated: true, account_id: account, csrf_token: csrf, expires_at: "2030-11-02T12:00:00Z" })
const response = (body: unknown, status = 200, headers = {}) => new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json", ...headers } })
const denied = () => response({ detail: "Authentication required" }, 401)
function dashboard(url: string) {
  const params = new URL(url, "http://localhost").searchParams
  return response({ ...page(params.get("start")!, params.get("end")!), offset: Number(params.get("offset")) })
}
function transport(overrides?: (url: string, init?: RequestInit) => Promise<Response> | Response | undefined) {
  return vi.fn<typeof fetch>().mockImplementation(async (input, init) => {
    const url = String(input)
    const result = overrides?.(url, init)
    if (result) return result
    if (url === "/auth/session") return denied()
    if (url === "/auth/signup") return response({ account_id: accountA, code: newCode }, 201)
    if (url === "/auth/login") return response(session())
    if (url === "/auth/logout") return new Response(null, { status: 204 })
    if (url.startsWith("/api/dashboard")) return dashboard(url)
    if (url.endsWith("/check")) return response({ front_id: front.id, ...JSON.parse(String(init?.body)) })
    if (url === "/api/fronts") return response({ ...front, ...JSON.parse(String(init?.body)) }, 201)
    throw new Error("Unexpected test request")
  })
}
async function enter() {
  await userEvent.type(await screen.findByLabelText("Código de acceso"), "test-private-code")
  await userEvent.click(screen.getByRole("button", { name: "Entrar" }))
}
const writes = (fetcher: ReturnType<typeof transport>) => fetcher.mock.calls.filter(([url, init]) => String(url).startsWith("/api/") && init?.method !== "GET")

const originalCredentials = Object.getOwnPropertyDescriptor(navigator, "credentials")
beforeEach(() => {
  // Radix measures its native checkbox input inside a form; jsdom has no layout.
  vi.stubGlobal("ResizeObserver", class { observe() {} unobserve() {} disconnect() {} })
})
afterEach(() => {
  if (originalCredentials) Object.defineProperty(navigator, "credentials", originalCredentials)
  else Reflect.deleteProperty(navigator, "credentials")
})
function passwordManager() {
  const store = vi.fn().mockResolvedValue(undefined)
  const get = vi.fn()
  const constructor = vi.fn(function (data: { id: string; password: string; name: string }) {
    return { ...data, type: "password" }
  })
  vi.stubGlobal("isSecureContext", true)
  vi.stubGlobal("PasswordCredential", constructor)
  Object.defineProperty(navigator, "credentials", { configurable: true, value: { store, get } })
  return { store, get, constructor }
}

describe("Guardar el código en el gestor del navegador", () => {
  it("ofrece el valor nativo solo tras confirmar la entrada, sin esperar al gestor ni guardar en la app", async () => {
    const manager = passwordManager()
    manager.store.mockReturnValue(new Promise(() => {}))
    const persistence = vi.spyOn(Storage.prototype, "setItem")
    let formAtCompletion: boolean | undefined
    const completion = vi.spyOn(window.history, "replaceState").mockImplementation(() => { formAtCompletion = !!document.querySelector("#login-form,#signup-code-form") })
    const login = deferred<Response>()
    const fetcher = transport(url => url === "/auth/login" ? login.promise : undefined)
    render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    const input = await screen.findByLabelText("Código de acceso") as HTMLInputElement
    Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, "value")!.set!.call(input, "autofilled-test-code")
    const href = window.location.href, historyState = window.history.state
    await userEvent.keyboard("{Enter}")
    expect(manager.store).not.toHaveBeenCalled()
    expect(completion).not.toHaveBeenCalled()
    await act(async () => { login.resolve(response(session())) })
    await screen.findByText("Guitarra")
    expect(manager.store).toHaveBeenCalledExactlyOnceWith(expect.objectContaining({ id: accountA, password: "autofilled-test-code", type: "password" }))
    expect(screen.queryByLabelText("Código de acceso")).toBeNull()
    expect(input.value).toBe("")
    expect(completion).toHaveBeenCalledExactlyOnceWith(historyState, "", href)
    expect(formAtCompletion).toBe(false)
    expect(persistence).not.toHaveBeenCalled()
    expect(manager.get).not.toHaveBeenCalled()
    expect(fetcher.mock.calls.filter(([url]) => url === "/auth/login")).toHaveLength(1)
  })
  it.each([401, 429, 503])("no ofrece guardar una entrada rechazada (%s)", async (status) => {
    const manager = passwordManager()
    const completion = vi.spyOn(window.history, "replaceState")
    const fetcher = transport(url => url === "/auth/login" ? response({}, status) : undefined)
    render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    await enter()
    await screen.findByRole("alert")
    expect(manager.store).not.toHaveBeenCalled()
    expect(completion).not.toHaveBeenCalled()
  })
  it("el alta usa un formulario de contraseña y solo ofrece guardarla tras ACK y prueba de su cuenta", async () => {
    const manager = passwordManager()
    let account = accountB
    const fetcher = transport(url => url === "/auth/login" ? response(session(csrfA, account)) : undefined)
    render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    await userEvent.click(await screen.findByRole("button", { name: "Crear cuenta" }))
    const input = await screen.findByLabelText("Tu código permanente") as HTMLInputElement
    expect(input.tagName).toBe("INPUT")
    expect(input.type).toBe("password")
    expect(input.autocomplete).toBe("new-password")
    expect(input.name).toBe("password")
    expect(input.form?.querySelector<HTMLInputElement>('[autocomplete="username"]')?.value).toBe(accountA)
    expect(input.readOnly).toBe(true)
    await userEvent.click(screen.getByRole("button", { name: "Mostrar código" }))
    expect(input.type).toBe("text")
    expect(input.value).toBe(newCode)
    await userEvent.click(screen.getByRole("button", { name: "Ocultar código" }))
    expect(input.type).toBe("password")
    expect(manager.store).not.toHaveBeenCalled()
    await userEvent.click(screen.getByRole("checkbox", { name: "He guardado mi código" }))
    await userEvent.click(screen.getByRole("button", { name: "Entrar en mi cuenta" }))
    await screen.findByRole("alert")
    expect(manager.store).not.toHaveBeenCalled()
    expect(input.value).toBe(newCode)
    account = accountA
    await userEvent.click(screen.getByRole("button", { name: "Entrar en mi cuenta" }))
    await screen.findByText("Guitarra")
    expect(manager.store).toHaveBeenCalledExactlyOnceWith(expect.objectContaining({ id: accountA, password: newCode }))
    expect(screen.queryByLabelText("Tu código permanente")).toBeNull()
  })
  it.each(["unsupported", "insecure", "rejected", "throws"])("la entrada sigue funcionando si el guardado está %s", async (failure) => {
    const manager = passwordManager()
    if (failure === "unsupported") vi.stubGlobal("PasswordCredential", undefined)
    if (failure === "insecure") vi.stubGlobal("isSecureContext", false)
    if (failure === "rejected") manager.store.mockRejectedValue(new DOMException("Unavailable", "NotAllowedError"))
    if (failure === "throws") manager.store.mockImplementation(() => { throw new Error("Unavailable") })
    render(<AuthenticatedApp authFactory={createAuthClient} fetcher={transport()} clock={clock} />)
    await enter()
    await screen.findByText("Guitarra")
    expect(screen.queryByRole("alert")).toBeNull()
    if (failure === "unsupported" || failure === "insecure") expect(manager.store).not.toHaveBeenCalled()
    expect(manager.get).not.toHaveBeenCalled()
  })
  it("una sesión recordada o revalidada no provoca otro guardado ni entrada automática", async () => {
    const manager = passwordManager()
    const fetcher = transport(url => url === "/auth/session" ? response(session()) : undefined)
    render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    await screen.findByText("Guitarra")
    fireEvent.focus(window)
    await waitFor(() => expect(fetcher.mock.calls.filter(([url]) => url === "/auth/session")).toHaveLength(2))
    await act(async () => {})
    expect(manager.store).not.toHaveBeenCalled()
    expect(manager.get).not.toHaveBeenCalled()
    expect(fetcher.mock.calls.filter(([url]) => url === "/auth/login")).toHaveLength(0)
  })
  it("no guarda una respuesta de entrada llegada después de desmontar la pantalla", async () => {
    const manager = passwordManager()
    const login = deferred<Response>()
    const fetcher = transport(url => url === "/auth/login" ? login.promise : undefined)
    const view = render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    await enter()
    view.unmount()
    await act(async () => { login.resolve(response(session())) })
    expect(manager.store).not.toHaveBeenCalled()
  })
  it("identifica la credencial por la cuenta realmente autenticada", async () => {
    const manager = passwordManager()
    const fetcher = transport(url => url === "/auth/login" ? response(session(csrfB, accountB)) : undefined)
    render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    await enter()
    await screen.findByText("Guitarra")
    expect(manager.store).toHaveBeenCalledExactlyOnceWith(expect.objectContaining({ id: accountB, password: "test-private-code" }))
  })
})

describe("Entrada privada sin perder solicitudes pendientes", () => {
  it.each(["focus", "pageshow", "visibilitychange"])("la comprobación %s de la misma sesión bloqueada conserva el código y su campo", async (event) => {
    const fetcher = transport(url => url === "/auth/session" ? response(session()) : undefined)
    const factory = (fetch: typeof globalThis.fetch) => ({ ...createAuthClient(fetch), canRead: () => false })
    render(<AuthenticatedApp authFactory={factory} fetcher={fetcher} clock={clock} />)
    const input = await screen.findByLabelText("Código de acceso") as HTMLInputElement
    await userEvent.type(input, "test-private-code")
    fireEvent(event === "visibilitychange" ? document : window, new Event(event))
    await waitFor(() => expect(fetcher.mock.calls.filter(([url]) => url === "/auth/session")).toHaveLength(2))
    await act(async () => {})
    expect(screen.getByLabelText("Código de acceso")).toBe(input)
    expect(document.activeElement).toBe(input)
    expect(input.value).toBe("test-private-code")
    expect(fetcher.mock.calls.some(([url]) => url === "/auth/login" || String(url).startsWith("/api/"))).toBe(false)
  })
  it("acepta autocompletado nativo sin eventos React, incluso tras renderizar de nuevo, y borra el campo al enviar", async () => {
    const login = deferred<Response>()
    const fetcher = transport(url => url === "/auth/login" ? login.promise : undefined)
    const view = render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    const input = await screen.findByLabelText("Código de acceso") as HTMLInputElement
    // Password managers can change the DOM value without a React change event.
    Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, "value")!.set!.call(input, "autofilled-test-code")
    view.rerender(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    expect(screen.getByLabelText("Código de acceso")).toBe(input)
    expect(input.value).toBe("autofilled-test-code")
    await userEvent.keyboard("{Enter}")
    expect(fetcher.mock.calls.filter(([url]) => url === "/auth/login").map(([, init]) => JSON.parse(String(init?.body)))).toEqual([{ code: "autofilled-test-code" }])
    expect(input.value).toBe("")
    expect(input.disabled).toBe(true)
    await act(async () => { login.resolve(response(session())) })
    await screen.findByText("Guitarra")
  })
  it("conserva el autocompletado cuando rota el CSRF de la misma sesión bloqueada", async () => {
    let csrf = csrfA
    let signedIn = true
    const fetcher = transport(url => {
      if (url === "/auth/session") return signedIn ? response(session(csrf)) : denied()
      if (url === "/auth/logout") { signedIn = false; return new Response(null, { status: 204 }) }
    })
    const factory = (fetch: typeof globalThis.fetch) => ({ ...createAuthClient(fetch), canRead: () => false })
    render(<AuthenticatedApp authFactory={factory} fetcher={fetcher} clock={clock} />)
    const input = await screen.findByLabelText("Código de acceso") as HTMLInputElement
    Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, "value")!.set!.call(input, "autofilled-test-code")
    csrf = csrfB
    fireEvent.focus(window)
    await waitFor(() => expect(fetcher.mock.calls.filter(([url]) => url === "/auth/session")).toHaveLength(2))
    await act(async () => {})
    expect(input.value).toBe("autofilled-test-code")
    expect(screen.getByLabelText("Código de acceso")).toBe(input)
    await userEvent.click(screen.getByRole("button", { name: "Cerrar sesión" }))
    const logout = fetcher.mock.calls.find(([url]) => url === "/auth/logout")!
    expect(new Headers(logout[1]?.headers).get("X-CSRF-Token")).toBe(csrfB)
    await screen.findByText("Sesión cerrada en este dispositivo.")
    expect((screen.getByLabelText("Código de acceso") as HTMLInputElement).value).toBe("")
  })
  it("borra el código al cambiar la cookie a otra cuenta bloqueada y no consulta sus datos", async () => {
    let account = accountA
    const fetcher = transport(url => url === "/auth/session" ? response(session(csrfA, account)) : undefined)
    const factory = (fetch: typeof globalThis.fetch) => ({ ...createAuthClient(fetch), canRead: () => false })
    render(<AuthenticatedApp authFactory={factory} fetcher={fetcher} clock={clock} />)
    const input = await screen.findByLabelText("Código de acceso") as HTMLInputElement
    Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, "value")!.set!.call(input, "autofilled-test-code")
    account = accountB
    fireEvent.focus(window)
    await screen.findByText(`Cuenta ${accountB.slice(0, 8)}`)
    expect((screen.getByLabelText("Código de acceso") as HTMLInputElement).value).toBe("")
    expect(fetcher.mock.calls.some(([url]) => url === "/auth/login" || String(url).startsWith("/api/"))).toBe(false)
  })
  it("la misma sesión bloqueada no borra el error ni el código ni el límite de intentos", async () => {
    const fetcher = transport(url => {
      if (url === "/auth/session") return response(session())
      if (url === "/auth/login") return response({}, 429, { "Retry-After": "60" })
    })
    const factory = (fetch: typeof globalThis.fetch) => ({ ...createAuthClient(fetch), canRead: () => false })
    render(<AuthenticatedApp authFactory={factory} fetcher={fetcher} clock={clock} />)
    await enter()
    await screen.findByRole("alert")
    const input = screen.getByLabelText("Código de acceso") as HTMLInputElement
    await userEvent.type(input, "next-test-code")
    fireEvent.focus(window)
    await waitFor(() => expect(fetcher.mock.calls.filter(([url]) => url === "/auth/session")).toHaveLength(2))
    await act(async () => {})
    expect(input.value).toBe("next-test-code")
    expect(screen.getByRole("alert").textContent).toMatch(/Demasiados intentos/)
    expect((screen.getByRole("button", { name: "Entrar" }) as HTMLButtonElement).disabled).toBe(true)
    expect(fetcher.mock.calls.filter(([url]) => url === "/auth/login")).toHaveLength(1)
  })
  it("permite cerrar una sesión recordada sin desbloquear para crear otra cuenta", async () => {
    let signedIn = true
    const fetcher = transport(url => {
      if (url === '/auth/session') return signedIn ? response(session()) : denied()
      if (url === '/auth/logout') { signedIn = false; return new Response(null, { status: 204 }) }
    })
    const factory = (fetch: typeof globalThis.fetch) => ({ ...createAuthClient(fetch), canRead: () => false })
    render(<AuthenticatedApp authFactory={factory} fetcher={fetcher} clock={clock} />)
    await screen.findByText(/Introduce tu código para descifrar/)
    expect(fetcher.mock.calls.some(([url]) => String(url).startsWith('/api/'))).toBe(false)
    await userEvent.click(screen.getByRole('button', { name: 'Cerrar sesión' }))
    await screen.findByText('Sesión cerrada en este dispositivo.')
    await userEvent.click(screen.getByRole('button', { name: 'Crear cuenta' }))
    await screen.findByLabelText('Tu código permanente')
    const logout = fetcher.mock.calls.find(([url]) => url === '/auth/logout')!
    expect(new Headers(logout[1]?.headers).get('X-CSRF-Token')).toBe(csrfA)
    expect(new Headers(logout[1]?.headers).get('X-Activity-Account')).toBe(accountA)
  })
  it("alta muestra el único código, copia y exige guardarlo antes de entrar; luego lo borra", async () => {
    const copy = vi.fn().mockResolvedValue(undefined)
    Object.defineProperty(navigator, "clipboard", { configurable: true, value: { writeText: copy } })
    const store = vi.spyOn(Storage.prototype, "setItem")
    const fetcher = transport()
    render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    await userEvent.click(await screen.findByRole("button", { name: "Crear cuenta" }))
    const shown = await screen.findByLabelText("Tu código permanente") as HTMLInputElement
    expect(shown.value).toBe(newCode)
    expect(shown.readOnly).toBe(true)
    expect(screen.getByText(/No hay recuperación/)).toBeTruthy()
    expect((screen.getByRole("button", { name: "Entrar en mi cuenta" }) as HTMLButtonElement).disabled).toBe(true)
    await userEvent.click(screen.getByRole("button", { name: "Copiar" }))
    expect(copy).toHaveBeenCalledExactlyOnceWith(newCode)
    const calls = fetcher.mock.calls.length
    fireEvent.focus(window); fireEvent(window, new Event("pageshow"))
    await act(async () => {})
    expect(fetcher.mock.calls).toHaveLength(calls)
    expect(fetcher.mock.calls.some(([url]) => url === "/auth/login" || String(url).startsWith("/api/"))).toBe(false)
    const unloading = new Event("beforeunload", { cancelable: true })
    fireEvent(window, unloading)
    expect(unloading.defaultPrevented).toBe(true)
    await userEvent.click(screen.getByRole("checkbox", { name: "He guardado mi código" }))
    await userEvent.click(screen.getByRole("button", { name: "Entrar en mi cuenta" }))
    await screen.findByText("Guitarra")
    expect(screen.queryByLabelText("Tu código permanente")).toBeNull()
    expect(document.body.textContent).not.toContain(newCode)
    expect(store).not.toHaveBeenCalled()
    expect(screen.queryByRole("button", { name: /recuperar|regenerar|reset/i })).toBeNull()
    const after = new Event("beforeunload", { cancelable: true })
    fireEvent(window, after)
    expect(after.defaultPrevented).toBe(false)
    expect(fetcher.mock.calls.filter(([url]) => url === "/auth/signup")).toHaveLength(1)
    expect(screen.getByText(/Cuenta aaaaaaaa/)).toBeTruthy()
  })
  it("no duplica un alta en curso y conserva Retry-After al volver al formulario de entrada", async () => {
    const signingUp = deferred<Response>()
    const fetcher = transport((url) => url === "/auth/signup" ? signingUp.promise : undefined)
    render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    const create = await screen.findByRole("button", { name: "Crear cuenta" })
    fireEvent.click(create); fireEvent.click(create)
    await screen.findByText(/Creando una cuenta vacía/)
    expect(fetcher.mock.calls.filter(([url]) => url === "/auth/signup")).toHaveLength(1)
    fireEvent.focus(window)
    await act(async () => { signingUp.resolve(response({}, 429, { "Retry-After": "60" })) })
    expect((await screen.findByRole("alert")).textContent).toMatch(/crear otra cuenta/)
    expect((screen.getByRole("button", { name: "Crear otra cuenta" }) as HTMLButtonElement).disabled).toBe(true)
    await userEvent.click(screen.getByRole("button", { name: "Volver a entrar" }))
    expect((screen.getByRole("button", { name: "Crear cuenta" }) as HTMLButtonElement).disabled).toBe(true)
    expect((screen.getByRole("button", { name: "Entrar" }) as HTMLButtonElement).disabled).toBe(false)
  })
  it("un alta incierta no se repite por foco y una nueva creación es explícitamente otra cuenta", async () => {
    const fetcher = transport((url) => url === "/auth/signup" ? Promise.reject(new TypeError("private-marker")) : undefined)
    render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    await userEvent.click(await screen.findByRole("button", { name: "Crear cuenta" }))
    expect((await screen.findByRole("alert")).textContent).toMatch(/Puede haberse creado.*otra cuenta/)
    fireEvent.focus(window); fireEvent(window, new Event("pageshow"))
    await act(async () => {})
    expect(fetcher.mock.calls.filter(([url]) => url === "/auth/signup")).toHaveLength(1)
    expect(screen.queryByText("Guitarra")).toBeNull()
    expect(document.body.textContent).not.toContain("private-marker")
    expect(screen.getByRole("button", { name: "Crear otra cuenta" })).toBeTruthy()
    const reload = new Event("beforeunload", { cancelable: true })
    fireEvent(window, reload)
    expect(reload.defaultPrevented).toBe(true)
  })
  it("sin portapapeles conserva el código y salir requiere advertir su pérdida", async () => {
    Object.defineProperty(navigator, "clipboard", { configurable: true, value: undefined })
    const confirm = vi.spyOn(window, "confirm").mockReturnValueOnce(false).mockReturnValueOnce(true)
    const fetcher = transport()
    render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    await userEvent.click(await screen.findByRole("button", { name: "Crear cuenta" }))
    await userEvent.click(await screen.findByRole("button", { name: "Copiar" }))
    await screen.findByText(/Selecciona el código/)
    await userEvent.click(screen.getByRole("button", { name: "Volver a entrar" }))
    expect(confirm).toHaveBeenCalledWith(expect.stringMatching(/No hay recuperación/))
    expect((screen.getByLabelText("Tu código permanente") as HTMLInputElement).value).toBe(newCode)
    await userEvent.click(screen.getByRole("button", { name: "Volver a entrar" }))
    await screen.findByLabelText("Código de acceso")
    expect(screen.queryByLabelText("Tu código permanente")).toBeNull()
    expect(fetcher.mock.calls.some(([url]) => url === "/auth/login")).toBe(false)
  })
  it("el login ACK que devuelve otra cuenta no activa datos ni pierde el código guardado", async () => {
    let logins = 0
    const fetcher = transport((url) => url === "/auth/login" ? response(++logins === 1 ? session(csrfB, accountB) : session()) : undefined)
    render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    await userEvent.click(await screen.findByRole("button", { name: "Crear cuenta" }))
    await userEvent.click(await screen.findByRole("checkbox", { name: "He guardado mi código" }))
    await userEvent.click(screen.getByRole("button", { name: "Entrar en mi cuenta" }))
    await screen.findByRole("alert")
    expect((screen.getByLabelText("Tu código permanente") as HTMLInputElement).value).toBe(newCode)
    expect((screen.getByRole("checkbox") as HTMLButtonElement).getAttribute("data-state")).toBe("checked")
    expect(fetcher.mock.calls.some(([url]) => String(url).startsWith("/api/"))).toBe(false)
    fireEvent.focus(window)
    await userEvent.click(screen.getByRole("button", { name: "Entrar en mi cuenta" }))
    await screen.findByText("Guitarra")
    expect(fetcher.mock.calls.filter(([url]) => url === "/auth/signup")).toHaveLength(1)
    expect(fetcher.mock.calls.filter(([url]) => url === "/auth/login").map(([, init]) => JSON.parse(String(init?.body)))).toEqual([{ code: newCode }, { code: newCode }])
  })
  it("409 antes de aceptar un cambio oculta A, comprueba B y no repite la escritura", async () => {
    let statuses = 0
    const fetcher = transport((url) => {
      if (url === "/auth/session") return response(++statuses === 1 ? session() : session(csrfB, accountB))
      if (url.endsWith("/check")) return response({ detail: "Account context changed" }, 409)
    })
    render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    await userEvent.click(await screen.findByRole("checkbox", { name: "Actividad en Guitarra" }))
    await screen.findByText(/La cuenta activa ha cambiado/)
    expect(screen.queryByText("Guitarra")).toBeNull()
    expect(writes(fetcher)).toHaveLength(1)
    expect(new Headers(writes(fetcher)[0][1]?.headers).get("X-Activity-Account")).toBe(accountA)
    expect(fetcher.mock.calls.filter(([url]) => String(url).startsWith("/api/"))).toHaveLength(2)
    await userEvent.click(screen.getByRole("button", { name: "Continuar con esta cuenta" }))
    await screen.findByText("Guitarra")
    expect(writes(fetcher)).toHaveLength(1)
  })
  it("alta confirmada empieza vacía y cerrar/entrar otra cuenta mantiene separados sus datos", async () => {
    let currentAccount: string | null = null
    const fetcher = transport((url, init) => {
      if (url === "/auth/session") return currentAccount ? response(session(csrfA, currentAccount)) : denied()
      if (url === "/auth/login") { currentAccount = JSON.parse(String(init?.body)).code === newCode ? accountA : accountB; return response(session(csrfA, currentAccount)) }
      if (url === "/auth/logout") { currentAccount = null; return new Response(null, { status: 204 }) }
      if (url.startsWith("/api/dashboard")) {
        const params = new URL(url, "http://localhost").searchParams
        const result = page(params.get("start")!, params.get("end")!)
        return response(currentAccount === accountA ? { ...result, items: [], total: 0 } : { ...result, items: [{ ...result.items[0], front: { ...front, name: "Solo cuenta B" } }] })
      }
    })
    render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    await userEvent.click(await screen.findByRole("button", { name: "Crear cuenta" }))
    await userEvent.click(await screen.findByRole("checkbox", { name: "He guardado mi código" }))
    await userEvent.click(screen.getByRole("button", { name: "Entrar en mi cuenta" }))
    await screen.findByText("No hay frentes en esta vista")
    await userEvent.click(screen.getByRole("button", { name: "Cerrar sesión" }))
    await screen.findByText("Sesión cerrada en este dispositivo.")
    await enter()
    await screen.findByText("Solo cuenta B")
    expect(screen.queryByText("No hay frentes en esta vista")).toBeNull()
    expect(screen.getByText(/Cuenta bbbbbbbb/)).toBeTruthy()
    const logout = fetcher.mock.calls.find(([url]) => url === "/auth/logout")!
    expect(new Headers(logout[1]?.headers).get("X-Activity-Account")).toBe(accountA)
    const lastRead = fetcher.mock.calls.filter(([url]) => String(url).startsWith("/api/")).at(-1)!
    expect(new Headers(lastRead[1]?.headers).get("X-Activity-Account")).toBe(accountB)
  })
  it("otra cuenta en segundo plano se anuncia y no hereda el borrador al continuar", async () => {
    let statuses = 0
    const fetcher = transport((url) => url === "/auth/session" ? response(++statuses === 1 ? session() : session(csrfB, accountB)) : undefined)
    render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    await userEvent.click(await screen.findByRole("button", { name: "Nuevo frente" }))
    await userEvent.type(screen.getByLabelText("Nombre"), "Borrador de A")
    const reads = fetcher.mock.calls.filter(([url]) => String(url).startsWith("/api/")).length
    fireEvent.focus(window)
    await screen.findByText(/La cuenta activa ha cambiado/)
    expect(screen.queryByText("Guitarra")).toBeNull()
    expect(screen.queryByRole("dialog")).toBeNull()
    expect(fetcher.mock.calls.filter(([url]) => String(url).startsWith("/api/"))).toHaveLength(reads)
    await userEvent.click(screen.getByRole("button", { name: "Continuar con esta cuenta" }))
    await screen.findByText("Guitarra")
    expect(screen.queryByRole("dialog")).toBeNull()
    await userEvent.click(screen.getByRole("button", { name: "Nuevo frente" }))
    expect((screen.getByLabelText("Nombre") as HTMLInputElement).value).toBe("")
    expect(new Headers(fetcher.mock.calls.filter(([url]) => String(url).startsWith("/api/" )).at(-1)?.[1]?.headers).get("X-Activity-Account")).toBe(accountB)
  })
  it("un cambio de cookie al iniciar transporte mantiene montada la solicitud de A aún en curso", async () => {
    const oldWrite = deferred<Response>(); let statuses = 0
    const fetcher = transport((url) => {
      if (url === "/auth/session") return response(++statuses === 1 ? session() : session(csrfB, accountB))
      if (url === "/auth/login") return response(session(csrfB))
      if (url.endsWith("/check")) { fireEvent(window, new Event("pageshow")); return oldWrite.promise }
    })
    render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    await userEvent.click(await screen.findByRole("checkbox", { name: "Actividad en Guitarra" }))
    await screen.findByLabelText("Código de acceso")
    expect(screen.getByText(/cuenta original/)).toBeTruthy()
    expect(screen.queryByRole("button", { name: "Continuar con esta cuenta" })).toBeNull()
    expect(fetcher.mock.calls.filter(([url]) => String(url).startsWith("/api/")).every(([, init]) => new Headers(init?.headers).get("X-Activity-Account") === accountA)).toBe(true)
    await act(async () => { oldWrite.reject(new TypeError("Lost response")) })
    await enter()
    await screen.findByText("Solicitud sin confirmar")
    expect(screen.getByRole("button", { name: "Reintentar solicitud" })).toBeTruthy()
    expect(writes(fetcher)).toHaveLength(1)
  })
  it("A incierta no se reintenta ni se pierde como B; volver a A conserva clave, cuerpo, día y cambia CSRF", async () => {
    const manager = passwordManager()
    let statuses = 0; let logins = 0; let attempts = 0
    const fetcher = transport((url) => {
      if (url === "/auth/session") return ++statuses === 1 ? response(session()) : response(session(csrfB, accountB))
      if (url === "/auth/login") return response(++logins === 1 ? session(csrfB, accountB) : session(csrfB))
      if (url.endsWith("/check") && ++attempts === 1) return Promise.reject(new TypeError("Lost"))
    })
    render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    await screen.findByText("Guitarra")
    fireEvent.change(screen.getByLabelText("Fecha de registro"), { target: { value: "2026-10-02" } })
    await waitFor(() => expect(screen.getByRole("checkbox").getAttribute("aria-disabled")).toBe("false"))
    await userEvent.click(screen.getByRole("checkbox"))
    await screen.findByText("Solicitud sin confirmar")
    fireEvent.focus(window)
    await screen.findByLabelText("Código de acceso")
    expect(screen.getByText(/cuenta original/)).toBeTruthy()
    expect(screen.queryByRole("button", { name: "Crear cuenta" })).toBeNull()
    await enter()
    await screen.findByLabelText("Código de acceso")
    expect(screen.queryByText("Guitarra")).toBeNull()
    expect(writes(fetcher)).toHaveLength(1)
    expect(manager.store).not.toHaveBeenCalled()
    await userEvent.type(screen.getByLabelText("Código de acceso"), "original-code")
    const count = fetcher.mock.calls.length
    fireEvent.focus(window)
    await act(async () => {})
    expect(fetcher.mock.calls).toHaveLength(count)
    expect((screen.getByLabelText("Código de acceso") as HTMLInputElement).value).toBe("original-code")
    await userEvent.click(screen.getByRole("button", { name: "Entrar" }))
    await userEvent.click(await screen.findByRole("button", { name: "Reintentar solicitud" }))
    await waitFor(() => expect(screen.getByRole("checkbox").getAttribute("aria-disabled")).toBe("false"))
    expect(screen.queryByText("Cambio confirmado por el servidor.")).toBeNull()
    const payloads = writes(fetcher).map(([, init]) => [init?.body, new Headers(init?.headers).get("Idempotency-Key"), new Headers(init?.headers).get("X-Activity-Account")])
    expect(payloads[1]).toEqual(payloads[0])
    expect(payloads[1][2]).toBe(accountA)
    expect(manager.store).toHaveBeenCalledExactlyOnceWith(expect.objectContaining({ id: accountA, password: "original-code" }))
    expect(new Headers(writes(fetcher)[1][1]?.headers).get("X-CSRF-Token")).toBe(csrfB)
    expect(fetcher.mock.calls.filter(([url]) => String(url).startsWith("/api/")).every(([, init]) => new Headers(init?.headers).get("X-Activity-Account") === accountA)).toBe(true)
  })
  it("un 204 tardío de cierre no anuncia que B haya cerrado sesión", async () => {
    const closing = deferred<Response>(); let statuses = 0
    const fetcher = transport((url) => {
      if (url === "/auth/session") return response(++statuses === 1 ? session() : session(csrfB, accountB))
      if (url === "/auth/logout") return closing.promise
    })
    render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    await userEvent.click(await screen.findByRole("button", { name: "Cerrar sesión" }))
    await act(async () => { closing.resolve(new Response(null, { status: 204 })) })
    await screen.findByText(/La cuenta activa ha cambiado/)
    expect(screen.queryByText("Sesión cerrada en este dispositivo.")).toBeNull()
    expect(fetcher.mock.calls.filter(([url]) => url === "/auth/logout")).toHaveLength(1)
  })
  it("el reintento de cierre que encuentra B no manda un cierre para B", async () => {
    let statuses = 0
    const fetcher = transport((url) => {
      if (url === "/auth/session") return response(++statuses === 1 ? session() : session(csrfB, accountB))
      if (url === "/auth/logout") return Promise.reject(new TypeError("Lost"))
    })
    render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    await userEvent.click(await screen.findByRole("button", { name: "Cerrar sesión" }))
    await userEvent.click(await screen.findByRole("button", { name: "Reintentar cierre" }))
    await screen.findByText(/La cuenta activa ha cambiado/)
    expect(fetcher.mock.calls.filter(([url]) => url === "/auth/logout")).toHaveLength(1)
    expect(screen.queryByText("Sesión cerrada en este dispositivo.")).toBeNull()
    expect(screen.queryByText("Guitarra")).toBeNull()
    await userEvent.click(screen.getByRole("button", { name: "Continuar con esta cuenta" }))
    await screen.findByText("Guitarra")
  })
  it("espera el estado de la cookie antes de consultar datos y presenta solo el código", async () => {
    const status = deferred<Response>()
    const fetcher = transport((url) => url === "/auth/session" ? status.promise : undefined)
    render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    expect(screen.getByRole("status").textContent).toContain("Comprobando")
    expect(fetcher.mock.calls.map(([url]) => url)).toEqual(["/auth/session"])
    await act(async () => { status.resolve(denied()) })
    const code = await screen.findByLabelText("Código de acceso") as HTMLInputElement
    expect(code.type).toBe("password")
    expect(code.name).toBe("password")
    expect(code.autocomplete).toBe("current-password")
    expect(code.maxLength).toBe(128)
    expect(screen.queryByText("Guitarra")).toBeNull()
    expect(screen.queryByLabelText(/correo|usuario/i)).toBeNull()
  })
  it("reanuda una cookie válida sin pedir código y mantiene el transporte del mismo origen", async () => {
    const fetcher = transport((url) => url === "/auth/session" ? response(session()) : undefined)
    render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    await screen.findByText("Guitarra")
    expect(screen.queryByLabelText("Código de acceso")).toBeNull()
    expect(fetcher.mock.calls.every(([, init]) => init?.credentials === "same-origin" && init.cache === "no-store" && init.redirect === "error")).toBe(true)
    expect(fetcher.mock.calls.some(([url]) => url === "/auth/login")).toBe(false)
  })
  it("borra el código al enviar, abre los datos solo tras éxito y escribe con CSRF", async () => {
    const login = deferred<Response>()
    const fetcher = transport((url) => url === "/auth/login" ? login.promise : undefined)
    render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    await enter()
    expect((screen.getByLabelText("Código de acceso") as HTMLInputElement).value).toBe("")
    expect(screen.queryByText("Guitarra")).toBeNull()
    await act(async () => { login.resolve(response(session())) })
    await userEvent.click(await screen.findByRole("checkbox", { name: "Actividad en Guitarra" }))
    await waitFor(() => expect(writes(fetcher)).toHaveLength(1))
    const [, init] = writes(fetcher)[0]
    expect(new Headers(init?.headers).get("X-CSRF-Token")).toBe(csrfA)
    expect(new Headers(init?.headers).get("Idempotency-Key")).toMatch(/^[0-9a-f-]{36}$/)
    expect(JSON.parse(String(init?.body))).toEqual({ day: "2026-10-03", marked: true })
  })
  it.each([
    [401, /Código incorrecto/], [429, /Demasiados intentos/], [503, /servidor.*esquema/i], [403, /origen/i],
  ])("el rechazo de entrada %s no inventa autenticación", async (status, message) => {
    const fetcher = transport((url) => url === "/auth/login" ? response({ detail: "private-marker" }, status, { "Retry-After": "5" }) : undefined)
    render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    await enter()
    expect((await screen.findByRole("alert")).textContent).toMatch(message)
    expect(screen.queryByText("Guitarra")).toBeNull()
    expect((screen.getByLabelText("Código de acceso") as HTMLInputElement).value).toBe("")
    expect(fetcher.mock.calls.some(([url]) => String(url).startsWith("/api/"))).toBe(false)
    expect(document.body.textContent).not.toContain("private-marker")
    if (status === 429) expect((screen.getByRole("button", { name: "Entrar" }) as HTMLButtonElement).disabled).toBe(true)
  })
  it("un error de red al entrar permite un intento explícito, no una sesión ficticia", async () => {
    const fetcher = transport((url) => url === "/auth/login" ? Promise.reject(new TypeError("private-marker")) : undefined)
    render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    await enter()
    expect((await screen.findByRole("alert")).textContent).toMatch(/conectar/)
    expect(screen.queryByText("Guitarra")).toBeNull()
    expect(document.body.textContent).not.toContain("private-marker")
    expect(fetcher.mock.calls.filter(([url]) => url === "/auth/login")).toHaveLength(1)
  })
  it("un 401 de comprobación en segundo plano no borra el código escrito ni el límite de intentos", async () => {
    const fetcher = transport((url) => url === "/auth/login" ? response({}, 429, { "Retry-After": "60" }) : undefined)
    render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    await enter()
    await screen.findByRole("alert")
    await userEvent.type(screen.getByLabelText("Código de acceso"), "next-test-code")
    fireEvent(window, new Event("pageshow"))
    await waitFor(() => expect(fetcher.mock.calls.filter(([url]) => url === "/auth/session")).toHaveLength(2))
    await act(async () => {})
    expect((screen.getByLabelText("Código de acceso") as HTMLInputElement).value).toBe("next-test-code")
    expect(screen.getByRole("alert").textContent).toMatch(/Demasiados intentos/)
    expect((screen.getByRole("button", { name: "Entrar" }) as HTMLButtonElement).disabled).toBe(true)
  })
  it("un esquema no disponible nunca ofrece inicializar cuentas desde terminal", async () => {
    const fetcher = transport((url) => url === "/auth/session" ? response({ detail: "Private access is not configured" }, 503) : undefined)
    render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    expect((await screen.findByRole("alert")).textContent).toMatch(/servidor.*esquema/i)
    expect(document.body.textContent).not.toMatch(/admin init|terminal|recuperación/i)
    expect(screen.getByRole("button", { name: "Reintentar conexión" })).toBeTruthy()
    expect(screen.queryByLabelText("Código de acceso")).toBeNull()
    expect(document.body.textContent).not.toContain("aún no está implementada")
    expect(fetcher.mock.calls).toHaveLength(1)
  })
  it("otro 503 explica servidor/esquema y README sin confundirlo con código incorrecto", async () => {
    const fetcher = transport((url) => url === "/auth/session" ? response({ detail: "Service unavailable" }, 503) : undefined)
    render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    expect((await screen.findByRole("alert")).textContent).toMatch(/servidor.*esquema/i)
    expect(screen.getByText(/README/)).toBeTruthy()
    expect(screen.queryByText(/Código incorrecto/)).toBeNull()
    expect(fetcher.mock.calls).toHaveLength(1)
  })
  it("conserva el editor y su borrador al revocarse la cookie en una comprobación de foco", async () => {
    let reads = 0
    const fetcher = transport((url) => url === "/auth/session" ? (++reads === 1 ? response(session()) : denied()) : undefined)
    render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    await screen.findByText("Guitarra")
    await userEvent.click(screen.getByRole("button", { name: "Nuevo frente" }))
    await userEvent.type(screen.getByLabelText("Nombre"), "Lectura pendiente")
    fireEvent.focus(window)
    await screen.findByLabelText("Código de acceso")
    expect(screen.queryByRole("dialog")).toBeNull()
    expect(screen.queryByText("Guitarra")).toBeNull()
    await enter()
    const dialog = await screen.findByRole("dialog")
    expect((within(dialog).getByLabelText("Nombre") as HTMLInputElement).value).toBe("Lectura pendiente")
  })
  it("una solicitud incierta bloquea el cierre y sobrevive a 401/login con misma clave, cuerpo y día", async () => {
    let attempts = 0
    const fetcher = transport((url) => {
      if (url === "/auth/session") return response(session())
      if (url === "/auth/login") return response(session(csrfB))
      if (url.endsWith("/check")) {
        attempts++
        if (attempts === 1) return Promise.reject(new TypeError("Lost response"))
        if (attempts === 2) return denied()
      }
    })
    render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    await screen.findByText("Guitarra")
    fireEvent.change(screen.getByLabelText("Fecha de registro"), { target: { value: "2026-10-02" } })
    await waitFor(() => expect(screen.getByRole("checkbox").getAttribute("aria-disabled")).toBe("false"))
    await userEvent.click(screen.getByRole("checkbox"))
    await screen.findByText("Solicitud sin confirmar")
    expect((screen.getByRole("button", { name: "Cerrar sesión" }) as HTMLButtonElement).disabled).toBe(true)
    await userEvent.click(screen.getByRole("button", { name: "Reintentar solicitud" }))
    await screen.findByLabelText("Código de acceso")
    expect(screen.queryByText("Guitarra")).toBeNull()
    await enter()
    const retry = await screen.findByRole("button", { name: "Reintentar solicitud" })
    expect(writes(fetcher)).toHaveLength(2)
    expect((screen.getByRole("button", { name: "Cerrar sesión" }) as HTMLButtonElement).disabled).toBe(true)
    await userEvent.click(retry)
    await waitFor(() => expect(writes(fetcher)).toHaveLength(3))
    const payloads = writes(fetcher).map(([, init]) => [init?.body, new Headers(init?.headers).get("Idempotency-Key")])
    expect(payloads[1]).toEqual(payloads[0]); expect(payloads[2]).toEqual(payloads[0])
    expect(JSON.parse(String(payloads[2][0]))).toEqual({ day: "2026-10-02", marked: true })
    expect(new Headers(writes(fetcher)[2][1]?.headers).get("X-CSRF-Token")).toBe(csrfB)
    await waitFor(() => expect(screen.getByRole("checkbox").getAttribute("aria-disabled")).toBe("false"))
    expect(screen.queryByText("Cambio confirmado por el servidor.")).toBeNull()
  })
  it("403 recupera el CSRF de otra pestaña sin repetir automáticamente la escritura", async () => {
    let statuses = 0; let checks = 0
    const fetcher = transport((url) => {
      if (url === "/auth/session") return response(session(++statuses === 1 ? csrfA : csrfB))
      if (url.endsWith("/check") && ++checks === 1) return response({ detail: "Request forbidden" }, 403)
    })
    render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    await userEvent.click(await screen.findByRole("checkbox"))
    await waitFor(() => expect(statuses).toBe(2))
    const checkbox = await screen.findByRole("checkbox")
    await waitFor(() => expect(checkbox.getAttribute("aria-disabled")).toBe("false"))
    expect(writes(fetcher)).toHaveLength(1)
    await userEvent.click(checkbox)
    await waitFor(() => expect(writes(fetcher)).toHaveLength(2))
    expect(new Headers(writes(fetcher)[1][1]?.headers).get("X-CSRF-Token")).toBe(csrfB)
  })
  it("descarta lecturas de autenticación anteriores a entrar y a cerrar sesión", async () => {
    let statuses = 0
    const beforeLogin = deferred<Response>(); const beforeLogout = deferred<Response>()
    const fetcher = transport((url) => {
      if (url === "/auth/session") {
        statuses++
        return statuses === 1 ? denied() : statuses === 2 ? beforeLogin.promise : statuses === 3 ? beforeLogout.promise : denied()
      }
    })
    render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    await screen.findByLabelText("Código de acceso")
    fireEvent.focus(window)
    await enter()
    await screen.findByText("Guitarra")
    await act(async () => { beforeLogin.resolve(denied()) })
    expect(screen.getByText("Guitarra")).toBeTruthy()
    fireEvent.focus(window)
    await userEvent.click(screen.getByRole("button", { name: "Cerrar sesión" }))
    await screen.findByText("Sesión cerrada en este dispositivo.")
    await act(async () => { beforeLogout.resolve(response(session())) })
    expect(screen.queryByText("Guitarra")).toBeNull()
    expect(screen.getByLabelText("Código de acceso")).toBeTruthy()
    const reads = fetcher.mock.calls.filter(([url]) => url === "/auth/session")
    expect(reads).toHaveLength(4)
    expect(reads.slice(1, 3).every(([, init]) => init?.signal?.aborted)).toBe(true)
  })
  it.each([401, 409])("un %s de una escritura antigua no cierra una nueva sesión", async (status) => {
    let statuses = 0
    const oldWrite = deferred<Response>()
    const fetcher = transport((url) => {
      if (url === "/auth/session") return ++statuses === 1 ? response(session()) : denied()
      if (url === "/auth/login") return response(session(csrfB))
      if (url.endsWith("/check")) return oldWrite.promise
    })
    render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    await userEvent.click(await screen.findByRole("checkbox"))
    expect((screen.getByRole("button", { name: "Cerrar sesión" }) as HTMLButtonElement).disabled).toBe(true)
    fireEvent.focus(window)
    await enter()
    await screen.findByText("Guitarra")
    await act(async () => { oldWrite.resolve(status === 401 ? denied() : response({ detail: "Account context changed" }, 409)) })
    expect(screen.queryByLabelText("Código de acceso")).toBeNull()
    expect(screen.getByText("Guitarra")).toBeTruthy()
    expect(screen.getByRole("checkbox").getAttribute("aria-disabled")).toBe("false")
  })
  it("aborta también la lectura de estado de un reintento de cierre al desmontarse", async () => {
    let statuses = 0
    const status = deferred<Response>()
    const fetcher = transport((url) => {
      if (url === "/auth/session") return ++statuses === 1 ? response(session()) : status.promise
      if (url === "/auth/logout") return Promise.reject(new TypeError("Lost response"))
    })
    const { unmount } = render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    await screen.findByText("Guitarra")
    await userEvent.click(screen.getByRole("button", { name: "Cerrar sesión" }))
    await userEvent.click(await screen.findByRole("button", { name: "Reintentar cierre" }))
    await waitFor(() => expect(statuses).toBe(2))
    const signal = fetcher.mock.calls.filter(([url]) => url === "/auth/session")[1][1]?.signal
    unmount()
    expect(signal?.aborted).toBe(true)
    await act(async () => { status.resolve(denied()) })
  })
  it("un cierre incierto oculta los datos y requiere reintento explícito sin anunciar éxito", async () => {
    let logouts = 0
    const fetcher = transport((url) => {
      if (url === "/auth/session") return logouts >= 2 ? denied() : response(session())
      if (url === "/auth/logout" && ++logouts === 1) return Promise.reject(new TypeError("Lost response"))
    })
    render(<AuthenticatedApp authFactory={createAuthClient} fetcher={fetcher} clock={clock} />)
    await screen.findByText("Guitarra")
    await userEvent.click(screen.getByRole("button", { name: "Cerrar sesión" }))
    await screen.findByRole("button", { name: "Reintentar cierre" })
    expect(screen.queryByText("Guitarra")).toBeNull()
    expect(screen.queryByText("Sesión cerrada en este dispositivo.")).toBeNull()
    const calls = fetcher.mock.calls.length
    fireEvent.focus(window); fireEvent(window, new Event("pageshow")); fireEvent(document, new Event("visibilitychange"))
    await act(async () => {})
    expect(fetcher.mock.calls).toHaveLength(calls)
    await userEvent.click(screen.getByRole("button", { name: "Reintentar cierre" }))
    await screen.findByText("Sesión cerrada en este dispositivo.")
    expect(screen.getByLabelText("Código de acceso")).toBeTruthy()
    expect(fetcher.mock.calls.filter(([url]) => url === "/auth/logout").map(([, init]) => new Headers(init?.headers).get("X-CSRF-Token"))).toEqual([csrfA, csrfA])
  })
})
