import { webcrypto, randomUUID } from 'node:crypto'
import { beforeEach, expect, it, vi } from 'vitest'
import { deriveCredentials, generateCode, decryptVault, encryptVault, MAX_VAULT_BYTES } from '../src/lib/privacy-crypto'
import { createPrivateApi, type PrivateDocument } from '../src/lib/private-vault'
import { createPrivateAuthClient } from '../src/lib/private-auth'
import { deferred } from './fixtures'

beforeEach(() => vi.stubGlobal('crypto', webcrypto))
const account = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'
const access = { accountId: account, csrfToken: 'A'.repeat(43) }
const draft = { name: 'Guitarra privada', reference: 'https://example.test/privado', state: 'open' as const }
function vaultServer() {
  let stored: Record<string, unknown> = { version: 0, legacy_revision: 0, iv: null, ciphertext: null, legacy: { fronts: [], checks: [], replays: [] } }
  let loseNext = false
  let day = '2026-10-06'
  const fetcher = vi.fn<typeof fetch>(async (url, init) => {
    if (url !== '/api/vault') throw new Error('Unexpected network path')
    if (init?.method === 'PUT') {
      const data = JSON.parse(String(init.body))
      if (data.version !== stored.version || data.day !== day) return Response.json({ detail: 'Vault changed' }, { status: 409 })
      stored = { version: Number(stored.version) + 1, legacy_revision: null, iv: data.iv, ciphertext: data.ciphertext, legacy: null }
      if (loseNext) { loseNext = false; throw new TypeError('Response lost after commit') }
      return Response.json({ version: stored.version })
    }
    return Response.json({ ...stored, day, now: `${day}T12:00:00Z` })
  })
  return { fetcher, lose() { loseNext = true }, stored: () => stored, replace(value: Record<string, unknown>) { stored = value }, advanceDay(value: string) { day = value } }
}
const period = { start: '2026-10-01', end: '2026-10-06' }
async function contents(server: ReturnType<typeof vaultServer>, key: CryptoKey) {
  const box = server.stored()
  return await decryptVault(key, account, Number(box.version), { iv: String(box.iv), ciphertext: String(box.ciphertext) }) as PrivateDocument
}
it.each(['open', 'standby', 'archived'] as const)('permanent deletion removes a %s front, its checks and replay content, preserving other records', async state => {
  const server = vaultServer(); const { key } = await deriveCredentials(generateCode())
  const api = createPrivateApi(server.fetcher, access, key)
  const createKey = randomUUID()
  const front = await api.createFront({ ...draft, state }, createKey)
  await api.writeCheck(front.id, '2026-10-04', true, randomUUID())
  await api.patchFront(front.id, { ...draft, name: 'Nombre a borrar', state })
  await api.trashFront!(front.id, randomUUID())
  const other = await api.createFront({ ...draft, name: 'Conservar', reference: null }, randomUUID())
  await api.writeCheck(other.id, '2026-10-03', true, randomUUID())
  const before = await contents(server, key)
  const unrelated = before.replays.filter(r => r.target === other.id.replaceAll('-', '') || 'id' in r.response && r.response.id === other.id)
  const request = randomUUID()
  expect(await api.deleteFront!(front.id, request)).toEqual({ front_id: front.id, deleted: true })
  const after = await contents(server, key)
  expect(after.fronts).toEqual([other])
  expect(after.checks).toEqual([{ front_id: other.id, day: '2026-10-03' }])
  expect(after.replays.filter(r => unrelated.some(old => old.key === r.key))).toEqual(unrelated)
  expect(JSON.stringify(after)).not.toContain(draft.name)
  expect(JSON.stringify(after)).not.toContain('Nombre a borrar')
  expect(JSON.stringify(after)).not.toContain(draft.reference)
  expect(JSON.stringify(after)).not.toContain('2026-10-04')
  expect(api.confirmedDashboard!(request, { ...period, trashed: true })?.total).toBe(0)
  const reloaded = createPrivateApi(server.fetcher, access, key)
  expect((await reloaded.dashboard(period)).items[0]).toMatchObject({ front: other, marked_dates: ['2026-10-03'] })
  server.fetcher.mockClear()
  await expect(reloaded.createFront({ ...draft, state }, createKey)).rejects.toMatchObject({ kind: 'deleted-request' })
  await expect(reloaded.restoreFront!(front.id, randomUUID())).rejects.toMatchObject({ kind: 'not-found' })
  expect(server.fetcher.mock.calls.every(([, init]) => init?.method === 'GET')).toBe(true)
})
it('a lost delete response is confirmed with the same key after reload, without deleting twice or reverting another tab', async () => {
  const server = vaultServer(); const { key } = await deriveCredentials(generateCode())
  const first = createPrivateApi(server.fetcher, access, key)
  const front = await first.createFront(draft, randomUUID())
  await first.trashFront!(front.id, randomUUID())
  const request = randomUUID(); server.lose()
  await expect(first.deleteFront!(front.id, request)).rejects.toMatchObject({ uncertain: true })
  expect(first.confirmedDashboard!(request, period)).toBeNull()
  const second = createPrivateApi(server.fetcher, access, key)
  const other = await second.createFront({ ...draft, name: 'Otra pestaña' }, randomUUID())
  const version = server.stored().version
  server.fetcher.mockClear()
  const reloaded = createPrivateApi(server.fetcher, access, key)
  expect(await reloaded.deleteFront!(front.id, request)).toEqual({ front_id: front.id, deleted: true })
  expect(server.stored().version).toBe(version)
  expect(server.fetcher.mock.calls.map(([, init]) => init?.method)).toEqual(['GET'])
  expect(reloaded.confirmedDashboard!(request, period)?.items.map(item => item.front.id)).toEqual([other.id])
  await expect(reloaded.deleteFront!(other.id, request)).rejects.toMatchObject({ kind: 'conflict' })
})
it.each(['open', 'standby', 'archived'] as const)('permanent deletion rejects a live %s front and never saves', async state => {
  const server = vaultServer(); const { key } = await deriveCredentials(generateCode())
  const api = createPrivateApi(server.fetcher, access, key)
  const front = await api.createFront({ ...draft, state }, randomUUID())
  const before = structuredClone(server.stored())
  server.fetcher.mockClear()
  await expect(api.deleteFront!(front.id, randomUUID())).rejects.toMatchObject({ kind: 'conflict' })
  expect(server.stored()).toEqual(before)
  expect(server.fetcher.mock.calls.map(([, init]) => init?.method)).toEqual(['GET'])
})
it('a stale cached check cannot resurrect a permanently deleted front', async () => {
  const server = vaultServer(); const { key } = await deriveCredentials(generateCode())
  const first = createPrivateApi(server.fetcher, access, key); const second = createPrivateApi(server.fetcher, access, key)
  const front = await first.createFront(draft, randomUUID())
  await first.dashboard(period)
  await second.trashFront!(front.id, randomUUID())
  await second.deleteFront!(front.id, randomUUID())
  const version = server.stored().version
  server.fetcher.mockClear()
  await expect(first.writeCheck(front.id, '2026-10-04', true, randomUUID())).rejects.toMatchObject({ kind: 'not-found' })
  expect(server.fetcher.mock.calls.map(([, init]) => init?.method)).toEqual(['PUT', 'GET'])
  expect(server.stored().version).toBe(version)
  expect((await contents(server, key)).fronts).toEqual([])
})
it.each([false, true])('a retired check always revalidates access even with a cached delete receipt (revoked: %s)', async revoked => {
  const server = vaultServer(); const { key } = await deriveCredentials(generateCode())
  let deny = false; const accessDenied = vi.fn()
  const api = createPrivateApi(async (url, init) => deny ? Response.json({}, { status: 401 }) : server.fetcher(url, init), { ...access, onAccessDenied: accessDenied }, key)
  const front = await api.createFront(draft, randomUUID()); const request = randomUUID()
  await api.writeCheck(front.id, '2026-10-04', true, request)
  await api.trashFront!(front.id, randomUUID())
  await api.deleteFront!(front.id, randomUUID())
  await api.dashboard(period)
  deny = revoked; server.fetcher.mockClear()
  await expect(api.writeCheck(front.id, '2026-10-04', true, request)).rejects.toMatchObject({ kind: revoked ? 'unauthorized' : 'deleted-request' })
  if (revoked) expect(accessDenied).toHaveBeenCalledExactlyOnceWith(401)
  else expect(server.fetcher.mock.calls.map(([, init]) => init?.method)).toEqual(['GET'])
})
it.each(['delete', 'restore'] as const)('a competing %s held before CAS cannot undo the other tab', async action => {
  const server = vaultServer(); const { key } = await deriveCredentials(generateCode())
  const second = createPrivateApi(server.fetcher, access, key)
  const front = await second.createFront(draft, randomUUID())
  await second.writeCheck(front.id, '2026-10-04', true, randomUUID())
  await second.trashFront!(front.id, randomUUID())
  const ready = deferred<void>(); const release = deferred<void>(); let hold = true
  const first = createPrivateApi(async (url, init) => {
    if (init?.method === 'PUT' && hold) { hold = false; ready.resolve(); await release.promise }
    return server.fetcher(url, init)
  }, access, key)
  const pending = action === 'delete' ? first.deleteFront!(front.id, randomUUID()) : first.restoreFront!(front.id, randomUUID())
  await ready.promise
  if (action === 'delete') await second.restoreFront!(front.id, randomUUID())
  else await second.deleteFront!(front.id, randomUUID())
  release.resolve()
  await expect(pending).rejects.toMatchObject({ kind: action === 'delete' ? 'conflict' : 'not-found' })
  const saved = await second.dashboard(period)
  expect(saved.total).toBe(action === 'delete' ? 1 : 0)
  if (action === 'delete') expect(saved.items[0].marked_dates).toEqual(['2026-10-04'])
  expect((await second.dashboard({ ...period, trashed: true })).total).toBe(0)
})
it('concurrent identical permanent deletions commit once and replay even without the front', async () => {
  const server = vaultServer(); const { key } = await deriveCredentials(generateCode())
  const first = createPrivateApi(server.fetcher, access, key); const second = createPrivateApi(server.fetcher, access, key)
  const front = await first.createFront(draft, randomUUID())
  await first.trashFront!(front.id, randomUUID())
  const version = Number(server.stored().version); const request = randomUUID()
  const results = await Promise.all([first.deleteFront!(front.id, request), second.deleteFront!(front.id, request)])
  expect(results).toEqual([{ front_id: front.id, deleted: true }, { front_id: front.id, deleted: true }])
  expect(server.stored().version).toBe(version + 1)
})
it('permanent deletion frees a place when all 200 fronts are occupied', async () => {
  const server = vaultServer(); const { key } = await deriveCredentials(generateCode())
  const fronts = Array.from({ length: 200 }, (_, index) => ({ ...draft, name: `Frente ${index}`, id: randomUUID(), created_at: '2026-10-01T00:00:00Z', updated_at: '2026-10-01T00:00:00Z', trashed_at: '2026-10-06T12:00:00Z' }))
  server.replace({ version: 0, legacy_revision: 0, iv: null, ciphertext: null, legacy: { fronts, checks: [], replays: [] } })
  const api = createPrivateApi(server.fetcher, access, key)
  await expect(api.createFront(draft, randomUUID())).rejects.toMatchObject({ kind: 'validation' })
  await api.deleteFront!(fronts[0].id, randomUUID())
  await api.createFront(draft, randomUUID())
  expect((await contents(server, key)).fronts).toHaveLength(200)
  expect((await api.dashboard({ ...period, trashed: true })).total).toBe(199)
})
it('permanent deletion frees ciphertext space at the real byte limit, retiring request IDs without their content', async () => {
  const server = vaultServer(); const { key } = await deriveCredentials(generateCode())
  const large = { name: 'X'.repeat(200), reference: `https://example.test/${'x'.repeat(2000)}`, state: 'open' as const }
  const front = { ...large, id: randomUUID(), created_at: '2026-10-01T00:00:00Z', updated_at: '2026-10-01T00:00:00Z', trashed_at: '2026-10-06T12:00:00Z' }
  const content: PrivateDocument = { format: 1, fronts: [front], checks: [], replays: [] }
  let consumed!: string
  while (true) {
    const replay = { key: randomUUID().replaceAll('-', ''), operation: 'patch_front' as const, target: front.id.replaceAll('-', ''), payload: large, response: front }
    if (new TextEncoder().encode(JSON.stringify({ ...content, replays: [...content.replays, replay] })).byteLength + 16 > MAX_VAULT_BYTES) break
    content.replays.push(replay); consumed = replay.key
  }
  const box = await encryptVault(key, account, 1, content)
  server.replace({ version: 1, legacy_revision: null, ...box, legacy: null })
  const api = createPrivateApi(server.fetcher, access, key)
  expect((await api.dashboard({ ...period, trashed: true })).total).toBe(1)
  await expect(api.createFront(large, randomUUID())).rejects.toMatchObject({ kind: 'validation' })
  await api.deleteFront!(front.id, randomUUID())
  const after = await contents(server, key)
  expect(JSON.stringify(after)).not.toContain(large.reference)
  expect(after.replays).toHaveLength(1)
  expect(after.replays[0].retired_keys).toContain(consumed)
  await api.createFront(large, randomUUID())
  expect((await api.dashboard(period)).total).toBe(1)
  expect(String(server.stored().ciphertext).length).toBeLessThan(box.ciphertext.length)
})
it('deleting at the logical replay cap compacts old receipts and permits new work', async () => {
  const server = vaultServer(); const { key } = await deriveCredentials(generateCode())
  const front = { ...draft, id: randomUUID(), created_at: '2026-10-01T00:00:00Z', updated_at: '2026-10-01T00:00:00Z', trashed_at: '2026-10-06T12:00:00Z' }
  // The legacy fixture isolates the logical 5000-response cap from byte quota.
  const replays = Array.from({ length: 5000 }, () => ({ key: randomUUID().replaceAll('-', ''), operation: 'patch_front', target: front.id.replaceAll('-', ''), payload: draft, response: front }))
  server.replace({ version: 0, legacy_revision: 0, iv: null, ciphertext: null, legacy: { fronts: [front], checks: [], replays } })
  const api = createPrivateApi(server.fetcher, access, key)
  await expect(api.createFront(draft, randomUUID())).rejects.toMatchObject({ kind: 'validation' })
  await api.deleteFront!(front.id, randomUUID())
  expect((await contents(server, key)).replays).toHaveLength(1)
  await api.createFront(draft, randomUUID())
  expect((await api.dashboard(period)).total).toBe(1)
})
it.each(['content', 'duplicate-key', 'bad-key', 'revived-front'] as const)('an inconsistent delete receipt (%s) is rejected without overwriting the document', async defect => {
  const server = vaultServer(); const { key } = await deriveCredentials(generateCode())
  const id = randomUUID(); const request = randomUUID().replaceAll('-', '')
  const receipt = { key: request, operation: 'delete_front', target: id.replaceAll('-', ''), payload: {}, response: { front_id: id, deleted: true }, retired_keys: [randomUUID().replaceAll('-', '')] }
  if (defect === 'content') Object.assign(receipt.response, { name: draft.name })
  if (defect === 'duplicate-key') receipt.retired_keys.push(request)
  if (defect === 'bad-key') receipt.retired_keys.push('bad-key')
  const fronts = defect === 'revived-front' ? [{ ...draft, id, created_at: '2026-10-01T00:00:00Z', updated_at: '2026-10-01T00:00:00Z' }] : []
  const box = await encryptVault(key, account, 1, { format: 1, fronts, checks: [], replays: [receipt] })
  server.replace({ version: 1, legacy_revision: null, ...box, legacy: null })
  const api = createPrivateApi(server.fetcher, access, key)
  await expect(api.dashboard(period)).rejects.toMatchObject({ kind: 'invalid-response' })
  await expect(api.createFront(draft, randomUUID())).rejects.toMatchObject({ kind: 'invalid-response' })
  expect(server.fetcher.mock.calls.every(([, init]) => init?.method === 'GET')).toBe(true)
})
it('a loaded encrypted check needs only its PUT and exposes the complete confirmed snapshot once', async () => {
  const server = vaultServer(); const { key } = await deriveCredentials(generateCode())
  const api = createPrivateApi(server.fetcher, access, key)
  const front = await api.createFront(draft, randomUUID())
  const loaded = await api.dashboard(period)
  loaded.items[0].front.name = 'Caller mutation must not enter the vault'
  server.fetcher.mockClear()
  const request = randomUUID()
  await api.writeCheck(front.id, '2026-10-06', true, request)
  expect(server.fetcher.mock.calls.map(([, init]) => init?.method)).toEqual(['PUT'])
  const confirmed = api.confirmedDashboard!(request, period)
  expect(confirmed?.items[0]).toMatchObject({ front: { name: draft.name }, count: 1, marked_dates: ['2026-10-06'], last_registered_day: '2026-10-06' })
  expect(api.confirmedDashboard!(request, period)).toBeNull()
  const next = randomUUID()
  await api.writeCheck(front.id, '2026-10-06', false, next)
  expect(api.confirmedDashboard!(next, period)?.items[0].marked_dates).toEqual([])
  expect(server.fetcher.mock.calls.map(([, init]) => init?.method)).toEqual(['PUT','PUT'])
  await api.dashboard(period)
  expect(server.fetcher.mock.calls.at(-1)?.[1]?.method).toBe('GET')
})
it('a stale cached check reloads after CAS conflict and preserves changes from another tab', async () => {
  const server = vaultServer(); const { key } = await deriveCredentials(generateCode())
  const first = createPrivateApi(server.fetcher, access, key); const second = createPrivateApi(server.fetcher, access, key)
  const front = await first.createFront(draft, randomUUID())
  await first.dashboard(period)
  await second.createFront({ ...draft, name: 'Otra pestaña' }, randomUUID())
  server.fetcher.mockClear()
  const request = randomUUID()
  await first.writeCheck(front.id, '2026-10-05', true, request)
  expect(server.fetcher.mock.calls.map(([, init]) => init?.method)).toEqual(['PUT','GET','PUT'])
  const confirmed = first.confirmedDashboard!(request, period)
  expect(confirmed?.total).toBe(2)
  expect(confirmed?.items.find(item => item.front.id === front.id)?.marked_dates).toEqual(['2026-10-05'])
})
it('midnight invalidates a cached synchronization day without moving the selected activity date', async () => {
  const server = vaultServer(); const { key } = await deriveCredentials(generateCode())
  const api = createPrivateApi(server.fetcher, access, key)
  const front = await api.createFront(draft, randomUUID())
  await api.dashboard(period)
  server.advanceDay('2026-10-07'); server.fetcher.mockClear()
  await api.writeCheck(front.id, '2026-10-06', true, randomUUID())
  expect(server.fetcher.mock.calls.map(([, init]) => init?.method)).toEqual(['PUT','GET','PUT'])
  expect((await api.dashboard(period)).items[0].marked_dates).toEqual(['2026-10-06'])
})
it('a lost check response exposes no confirmation; retry projects current data rather than its old replay', async () => {
  const server = vaultServer(); const { key } = await deriveCredentials(generateCode())
  const first = createPrivateApi(server.fetcher, access, key); const second = createPrivateApi(server.fetcher, access, key)
  const front = await first.createFront(draft, randomUUID())
  await first.dashboard(period)
  const request = randomUUID(); server.lose()
  await expect(first.writeCheck(front.id, '2026-10-06', true, request)).rejects.toMatchObject({ uncertain: true })
  expect(first.confirmedDashboard!(request, period)).toBeNull()
  await second.writeCheck(front.id, '2026-10-06', false, randomUUID())
  server.fetcher.mockClear()
  expect(await first.writeCheck(front.id, '2026-10-06', true, request)).toMatchObject({ marked: true })
  expect(first.confirmedDashboard!(request, period)?.items[0].marked_dates).toEqual([])
  expect(server.fetcher.mock.calls.map(([, init]) => init?.method)).toEqual(['GET'])
})
it('forgetting the memory snapshot makes the next check read afresh', async () => {
  const server = vaultServer(); const { key } = await deriveCredentials(generateCode())
  const api = createPrivateApi(server.fetcher, access, key)
  const front = await api.createFront(draft, randomUUID())
  await api.dashboard(period); api.forgetSnapshot!(); server.fetcher.mockClear()
  await api.writeCheck(front.id, '2026-10-06', true, randomUUID())
  expect(server.fetcher.mock.calls.map(([, init]) => init?.method)).toEqual(['GET','PUT'])
})
it('replaying a cached request reads current data instead of confirming a stale checkbox', async () => {
  const server = vaultServer(); const { key } = await deriveCredentials(generateCode())
  const first = createPrivateApi(server.fetcher, access, key); const second = createPrivateApi(server.fetcher, access, key)
  const front = await first.createFront(draft, randomUUID())
  const request = randomUUID()
  await first.writeCheck(front.id, '2026-10-06', true, request)
  await first.dashboard(period)
  await second.writeCheck(front.id, '2026-10-06', false, randomUUID())
  server.fetcher.mockClear()
  expect(await first.writeCheck(front.id, '2026-10-06', true, request)).toMatchObject({ marked: true })
  expect(first.confirmedDashboard!(request, period)?.items[0].marked_dates).toEqual([])
  expect(server.fetcher.mock.calls.map(([, init]) => init?.method)).toEqual(['GET'])
})
it.each(['open','standby','archived'] as const)('trash and restore preserve %s, the identity and all checks in ciphertext', async state => {
  const server = vaultServer(); const { key } = await deriveCredentials(generateCode())
  const api = createPrivateApi(server.fetcher, access, key)
  const front = await api.createFront({ ...draft, state }, randomUUID())
  await api.writeCheck(front.id, '2026-10-04', true, randomUUID())
  const request = randomUUID()
  await api.trashFront!(front.id, request)
  expect((await api.dashboard(period)).total).toBe(0)
  const trash = await api.dashboard({ ...period, trashed: true })
  expect(trash.items[0]).toMatchObject({ front: { id: front.id, name: draft.name, state, trashed_at: '2026-10-06T12:00:00Z' }, marked_dates: ['2026-10-04'] })
  await expect(api.writeCheck(front.id, '2026-10-04', false, randomUUID())).rejects.toMatchObject({ kind: 'not-found' })
  await expect(api.patchFront(front.id, { ...draft, name: 'Alterado' })).rejects.toMatchObject({ kind: 'not-found' })
  await api.restoreFront!(front.id, randomUUID())
  const restored = await api.dashboard(period)
  expect(restored.items[0]).toMatchObject({ front: { id: front.id, state, name: draft.name, created_at: front.created_at, trashed_at: null }, marked_dates: ['2026-10-04'] })
  await api.trashFront!(front.id, request)
  expect(api.confirmedDashboard!(request, period)?.total).toBe(1)
  expect((await api.dashboard({ ...period, trashed: true })).total).toBe(0)
  const bodies = server.fetcher.mock.calls.filter(([, init]) => init?.method === 'PUT').map(([,init]) => String(init?.body)).join('\n')
  expect(bodies).not.toContain(draft.name)
  expect(bodies).not.toContain('trashed_at')
})
it('lost encrypted response replays the original result without duplicate creates or undoing later edits/checks', async () => {
  const server = vaultServer()
  const { key } = await deriveCredentials(generateCode())
  const api = createPrivateApi(server.fetcher, access, key)
  const createKey = randomUUID()
  server.lose()
  await expect(api.createFront(draft, createKey)).rejects.toMatchObject({ kind: 'network', uncertain: true })
  const front = await api.createFront(draft, createKey)
  expect(server.stored().version).toBe(1)
  await api.patchFront(front.id, { ...draft, name: 'Nombre editado' })
  expect((await api.createFront(draft, createKey)).name).toBe(draft.name)
  const checkKey = randomUUID()
  const marked = await api.writeCheck(front.id, 'today', true, checkKey)
  await api.writeCheck(front.id, 'today', false, randomUUID())
  expect(await api.writeCheck(front.id, 'today', true, checkKey)).toEqual(marked)
  const page = await api.dashboard({ start: '2026-10-01', end: '2026-10-31' })
  expect(page.total).toBe(1)
  expect(page.items[0].front.name).toBe('Nombre editado')
  expect(page.items[0].marked_dates).toEqual([])
  const putBodies = server.fetcher.mock.calls.filter(([, init]) => init?.method === 'PUT').map(([, init]) => String(init?.body)).join('\n')
  expect(putBodies).not.toContain(draft.name)
  expect(putBodies).not.toContain(draft.reference)
  // The synchronization day is metadata; actual activity dates live in ciphertext.
  expect(putBodies).not.toContain('marked')
  await expect(api.createFront({ ...draft, name: 'Conflict' }, createKey)).rejects.toMatchObject({ kind: 'conflict' })
  await expect(api.writeCheck(front.id, '2026-10-07', true, randomUUID())).rejects.toMatchObject({ kind: 'validation' })
})
it('concurrent tabs merge independent mutations and deduplicate an identical operation', async () => {
  const server = vaultServer()
  const { key } = await deriveCredentials(generateCode())
  const first = createPrivateApi(server.fetcher, access, key)
  const second = createPrivateApi(server.fetcher, access, key)
  const same = randomUUID()
  const [a, b] = await Promise.all([first.createFront(draft, same), second.createFront(draft, same)])
  expect(a).toEqual(b)
  await Promise.all([first.createFront({ ...draft, name: 'Segundo' }, randomUUID()), second.createFront({ ...draft, name: 'Tercero' }, randomUUID())])
  expect((await first.dashboard({ start: '2026-10-01', end: '2026-10-31' })).total).toBe(3)
})
it('creation order stays chronological across mixed legacy precision before pagination, including microseconds', async () => {
  const server = vaultServer()
  const { key } = await deriveCredentials(generateCode())
  const make = (symbol: string, created_at: string) => ({ ...draft, id: `${symbol.repeat(8)}-${symbol.repeat(4)}-4${symbol.repeat(3)}-8${symbol.repeat(3)}-${symbol.repeat(12)}`, created_at, updated_at: created_at })
  const early = make('f', '2026-10-06T12:00:00Z')
  const middle = make('b', '2026-10-06T12:00:00.000001Z')
  const late = make('a', '2026-10-06T12:00:00.000002Z')
  server.replace({ version: 0, legacy_revision: 3, iv: null, ciphertext: null, legacy: { fronts: [late, middle, early], checks: [], replays: [] } })
  const api = createPrivateApi(server.fetcher, access, key)
  for (const order of ['created', 'activity_desc'] as const) {
    const ids = []
    for (let offset = 0; offset < 3; offset++) ids.push((await api.dashboard({ start: '2026-10-01', end: '2026-10-31', limit: 1, offset, order })).items[0].front.id)
    expect(ids).toEqual([early.id, middle.id, late.id])
  }
})
it('migration encrypts content and original replays; corrupted ciphertext never becomes an empty replacement', async () => {
  const server = vaultServer()
  const { key } = await deriveCredentials(generateCode())
  const front = { ...draft, id: randomUUID(), created_at: '2026-10-01T00:00:00Z', updated_at: '2026-10-01T00:00:00Z' }
  server.replace({ version: 0, legacy_revision: 2, iv: null, ciphertext: null, legacy: { fronts: [front], checks: [{ front_id: front.id, day: '2026-10-02' }], replays: [] } })
  const api = createPrivateApi(server.fetcher, access, key)
  expect((await api.dashboard({ start: '2026-10-01', end: '2026-10-31' })).items[0].count).toBe(1)
  expect(server.stored().legacy).toBeNull()
  const stored = server.stored()
  const plain = await decryptVault(key, account, Number(stored.version), { iv: String(stored.iv), ciphertext: String(stored.ciphertext) })
  expect(plain).toMatchObject({ fronts: [front] })
  server.replace({ ...stored, ciphertext: 'A'.repeat(String(stored.ciphertext).length) })
  const before = server.fetcher.mock.calls.filter(([, init]) => init?.method === 'PUT').length
  await expect(api.dashboard({ start: '2026-10-01', end: '2026-10-31' })).rejects.toMatchObject({ kind: 'invalid-response' })
  await expect(api.createFront(draft, randomUUID())).rejects.toMatchObject({ kind: 'invalid-response' })
  expect(server.fetcher.mock.calls.filter(([, init]) => init?.method === 'PUT')).toHaveLength(before)
})
it('private auth generates the code locally and sends only derived credentials; reloading loses the decryption key', async () => {
  const session = { authenticated: true, account_id: account, csrf_token: 'A'.repeat(43), expires_at: '2030-11-02T12:00:00Z' }
  const fetcher = vi.fn<typeof fetch>(async url => {
    if (url === '/auth/config') return Response.json({ local: true, registration_enabled: true, sitekey: null })
    if (url === '/auth/signup') return Response.json({ account_id: account }, { status: 201 })
    return Response.json(session)
  })
  const storage = vi.spyOn(Storage.prototype, 'setItem')
  const auth = createPrivateAuthClient(fetcher)
  const created = await auth.signup()
  expect(auth.canRead!(account)).toBe(false)
  await auth.login(created.code)
  expect(auth.canRead!(account)).toBe(true)
  expect(JSON.stringify(fetcher.mock.calls)).not.toContain(created.code)
  expect(JSON.stringify(fetcher.mock.calls)).not.toContain(created.code.replaceAll('-', ''))
  const requests = fetcher.mock.calls.filter(([url]) => url === '/auth/signup' || url === '/auth/login').map(([, init]) => JSON.parse(String(init?.body)))
  expect(requests[0].credential).toBe(requests[1].credential)
  expect(storage).not.toHaveBeenCalled()
  const reloaded = createPrivateAuthClient(fetcher)
  expect(await reloaded.session()).toEqual(session)
  expect(reloaded.canRead!(account)).toBe(false)
  auth.lock!()
  expect(auth.canRead!(account)).toBe(false)
})
